### ISSUE TITLE
Annotate/Highlight by keyword search or some rules

### ISSUE THREAD

**Issue by ritaappzen** [chakki-works/doccano#104]
Feature request: it would be very beneficial to find certain words or values, have the annotation tool select them all and annotate them. For example, instead of manually annotating the word "red", a function would be created to annotate every "red" within the text.

**Comment by icoxfog417** [comment]
Thank you for the feature request! I edited the title to clarify your request.

[snorkel](https://github.com/HazyResearch/snorkel) has same concept. It'll be good reference.

**Comment by ritaappzen** [comment]
Thats perfect, thanks so much!

**Comment by icoxfog417** [comment]
Continue on #224.

**Comment by miskib** [comment]
Outside of snorkel, is there any option to do it with a mouseclick / using keyboard shortcuts?

**Comment by ningkko** [comment]
How should we use this feature? Really need some hints for the annotators.
