### ISSUE TITLE
Forgot the Password ,How to create new password or setup a new password?

### ISSUE THREAD

**Issue by deepakgupta360** [chakki-works/doccano#107]
If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**: 

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by BrambleXu** [comment]
Please describe your question in detail rather than post the issue template.  You can reset your password from command line. Find more info [here](https://stackoverflow.com/a/35969131)
