### ISSUE TITLE
Read annotated data with Doccano in Spacy

### ISSUE THREAD

**Issue by mrfast7** [chakki-works/doccano#109]
Hi,
Please how can i read my annotated data with another tool named Doccano.
**1) Here is my annotated data's form:**

> "annotation": [
> [
> 79,
> 99,
> "Nom complet"
> ],

**2) The code that i want to change to read my annotated data:**

>     for line in lines:
>         data = json.loads(line)
>         text = data['content']
>         entities = []
>         for annotation in data['annotation']:
>             #only a single point in text annotation.
>             point = annotation['points'][0]
>             labels = annotation['label']
>             # handle both list of labels or a single label.
>             if not isinstance(labels, list):
>                 labels = [labels]
> 
>             for label in labels:
>                 #dataturks indices are both inclusive [start, end] but spacy is not [start, end)
>                 entities.append((point['start'], point['end'] + 1 ,label))

**Comment by BrambleXu** [comment]
You should read this [Export File Format](https://github.com/chakki-works/doccano/wiki/Export-File-Formats#export-file-format)

**Comment by mrfast7** [comment]
BrambleXu can you help me please ?
