### ISSUE TITLE
Alignment for import data format and export data format

### ISSUE THREAD

**Issue by BrambleXu** [chakki-works/doccano#113]
Right row doccano support for importing labeled dataset, and it is a wonderful feature for the [human in the loop](https://github.com/chakki-works/doccano/issues/11#issuecomment-464106275). 

But I noticed that the import data format is different from the export data format. Take the sequence labeling task as an example.

The labeled data format is like below. 
```
{"text": "EU rejects German call to boycott British lamb.", "labels": [ [0, 2, "ORG"], [11, 17, "MISC"]]}
{"text": "Peter Blackburn", "labels": [ [0, 15, "PERSON"] ]}
{"text": "President Obama", "labels": [ [10, 15, "PERSON"] ]}
```
The output data format looks like this. I will call it `format 0` in below.
```
{"id": 15, "text": "EU rejects German call to boycott British lamb.", "annotations": [{"label": 7, "start_offset": 0, "end_offset": 2, "user": 1}, {"label": 6, "start_offset": 11, "end_offset": 17, "user": 1}], "meta": {}}
{"id": 16, "text": "Peter Blackburn", "annotations": [{"label": 8, "start_offset": 0, "end_offset": 15, "user": 1}], "meta": {}}
{"id": 17, "text": "President Obama", "annotations": [{"label": 8, "start_offset": 10, "end_offset": 15, "user": 1}], "meta": {}}
```
The major problem is that the output only show the label id, rather than the label name. So if I want to import this data into doccano again, I have to figure out which label belong to which word. And the output key name is `annotations` instead of `labels`. It would be better to make them use the same key name for the consistency.  We can use `labels` as the key for import data, export data and in classification task and sequecne to sequence task. 

# Method 1

The output format could like this, `format 1`:
```
{
"doc_id": 15, "text": "EU rejects German call to boycott British lamb.",  
"labels": [[0, 2, "ORG"], [11, 17, "MISC"]], 
"meta": {}
}
```
This format can **derectly import to doccano again**, and can be read by spaCy easliy. 

![image](https://user-images.githubusercontent.com/10768193/54412012-882c8000-4734-11e9-9da8-b8bdc1456203.png)

The output is like this
```
{
"doc_id": 18, 
"text": "EU rejects German call to boycott British lamb.",  
"labels": [[0, 2, "ORG"], [11, 17, "MISC"], [34, 41, "ORG"], 
"meta": {}
}
```
This is the most simple format. We only need to change the export code.

Another format for this is using the dictionary to save the label information, just like `format 0`. It would make the export data more readable and we need to change the format of import data to be the same with `format 0`. 

```
{
"text": "EU rejects German call to boycott British lamb.", 
"annotations": [{"label_name": "label1", "start_offset": 0, "end_offset": 2}, {"label_name": "label2", "start_offset": 11, "end_offset": 17, "user": 1}], 
"meta": {}
}
```

But we can't know who annotate which label in this way.

# Method 2

We can save the `doc_id`, `label_id`, `user_id` in `meta` key. 

The output data `format 2`

```
{
"doc_id": 18, "text": "EU rejects German call to boycott British lamb.",  
 "labels": [[0, 2, "ORG", "user1"], [11, 17, "MISC", "user2"]], 
 "meta": {"label_id": {"MISC": 6, "ORG":8,}, "user_id": {"user1": 1, "user2":2}}
}
```

But this format needs to change the import data code to deal with the "user1" value in `[0, 2, "ORG", "user1"]` if the user provides this value. 

The goal is directly to import this data format to doccano again. 

# Method 3

The user can write the script to translate the export format to import format. But still, we should provide enough information in the export data. We should include the label name into `format 0` and the `labels` or `annotations` key name should be consistent. 

# Method 4 

Two download buttons, one button for the simple export format (`format 1`) so the user can directly import the data into doccano again, and use spaCy deal with data easily. The second button for the detailed export format (`format 0` with label name). Users should write the script by themselves.

**Comment by lfoppiano** [comment]
Hi, first of all I wanted to thank you for this great tool. It was long missing a good looking and usable annotation tool. 
I latch-up in this discussion as I'm also trying to adapt doccano to our workflow and I have some comments. 

1. the information for the export should be self explanatory, so the label should be in the output (maybe it was just overlooked?) - you can still keep the internal id, though
2. we should enable custom tokenisation, that means that if my training data is in sync with other part of my machinery it will be guarantee that such synchronization will be maintained.  The tokenisation is also more robust and would allow to ship more information for each token (for example ortogonal features like formatting etc..) 

My proposal is to follow the prodigy format instead. 
```
{
"spans": [{"start": 58, "end": 72, "token_start": 16, "token_end": 25, "label": "label1"}], [...]
"tokens": [{"text": "We", "start": 0, "end": 2, "id": 0}, {"text": " ", "start": 2, "end": 3, "id": 1}] , [...]
"text": "We have measured the [...]"
}
```

the `token_start/token_end` are the index of the tokens while the `start/end` is the positional index in the text. Even if the token are not supplied, whatever tokeniser is used inside doccano should be used to export the data and maintain the consistency.

Lastly having user information would be additionally great if we want to compute IAA measures from the exported data ;-) 

Cheers
Luca

**Comment by JoshuaPostel** [comment]
My vote would be for method 2. 

In addition to containing sufficient information, it would enable doccano to play nicely with other tools and systems. For example, after a little reformatting, annotations from an external system (by a human or by a model) could be imported into doccano. In the context of human-in-the-loop, this would allow doccano to measure agreement between models and annotators (see #114).

**Comment by JoshuaPostel** [comment]
@lfoppiano given that doccano does not currently have any features or support for tokenization, I believe that it should be discussed in a separate issue.

**Comment by lfoppiano** [comment]
I'm sorry I didn't explain. I meant Inter Annotation Agreement measures. Thanks for your feedback Sent from my Mobile

**Comment by c-w** [comment]
Given that https://github.com/chakki-works/doccano/pull/217 has been merged, can this issue be closed?
