### ISSUE TITLE
I am not able to upload files.

### ISSUE THREAD

**Issue by nareshmungpara** [chakki-works/doccano#115]
![no_upload_button](https://user-images.githubusercontent.com/34807837/54528630-7f8db100-49a3-11e9-8d04-9512ea9af90d.PNG)

There is no upload button coming as it is suggested in guide

**Comment by Hironsan** [comment]
> There is no upload button coming as it is suggested in guide

Yes, there is no upload button after PR https://github.com/chakki-works/doccano/pull/110 .

After selecting a file, the file will be automatically uploaded.

**Comment by BrambleXu** [comment]
We will update the guide soon.

**Comment by sugiyamath** [comment]
I think this question means "nothing happen when uploaded a file".
If the file format is wrong, it must show us what wrong.

**Comment by Hironsan** [comment]
> I think this question means "nothing happened when uploaded a file".

I think so too. That's why I ask him "Are there any other problems?".
We cannot help @nareshmungpara unless he provides more information such as file format, file size, his environment and so on.

**Comment by adaj** [comment]
Hi! I had the same problem, selecting a file and not receiving any feedback from the uploader regarding the upload success. After a while, I noticed that the uploader does not read some characters, such as "ã", "é" etc. I tried 

`
{"text": "Lorem ipsum"}\n{"text": "John Doe"}\n{"text": "é ã test."}
`

but it didn't upload and also don't respond with errors. Then, I tested

`
{"text": "Lorem ipsum"}\n{"text": "John Doe"}\n{"text": "e a test."}
`

and it uploads properly. What are your thoughts on it?

**Comment by billlyzhaoyh** [comment]
I went back and forth many times on uploading data and finally managed to upload.

The error I always encounter is 'This field cannot be empty' which is probably I have some values missing in the data frame which I didn't check but it could also be doccano cannot understand emojis.

It will be great if this error message can be changed into something more informative!
