### ISSUE TITLE
Even with Superuser Access, users can't add label for any projects(even for own project)

### ISSUE THREAD

**Issue by albertnanda** [chakki-works/doccano#116]
Hi,

User with Superuser access cannot add/remove labels for own projects.

Thanks,
AN

**Comment by BrambleXu** [comment]
It works well in my machine. Please give more information.

**Comment by albertnanda** [comment]
Dev server using: python manage.py runserver

I have created a new user, with superuser permission. Whenever, I try to add/remove a label, I get this message on console:
Forbidden: /api/projects/2/labels/
Also, note if I make the user a staff_user, I can then add/remove user

**Comment by icoxfog417** [comment]
Please raise a new issue if you still face this phenomenon.
