### ISSUE TITLE
New project structure

### ISSUE THREAD

**Issue by Hironsan** [chakki-works/doccano#123]
This issue is the first step to the *Introduce JavaScript testing framework* task I wrote in the [Feature Ideas](https://github.com/chakki-works/doccano/projects/2#card-16405365).

I think the current project structure is somewhat hard to understand for both Django and Vue.js developers and difficult to decide where to place the frontend testing code. To make it easier to understand project structure and to place the testing code, the project structure should be changed to something more clear like follows:

```
doccano/
  backend/
    app/
      __init__.py
      settings.py
      urls.py
      wsgi.py
    api/         # doccano core api; Project, Documents, ...
      tests/
      admin.py
      exceptions.py
      filters.py
      models.py
      permissions.py
      serializers.py
      urls.py
      utils.py
      views.py
    router/ 
      templates/
      static/
      tests/
      apps.py
      urls.py
      views.py
    management/
    __init__.py
    manage.py
  frontend/  # Client Side Vue/Javascript, build could be written to static/ folder
    src/
      assets/
      components/
    tests/
      units/
    package.json
    package-lock.json
    webpack.config.js
  docs/
  scripts/
  Pipfile
  Pipfile.lock
  ...
```

This structure is based on [cookiecutter-django-vue](https://github.com/vchaptsev/cookiecutter-django-vue).

**Comment by frco9** [comment]
@Hironsan, could you clarify the status of this refactorization? Shall we use the code from the `frontend` directory or update components is the `app/server/statics` directory? 
I'd like to do some improvements and a PR but this point is not very clear for me? !
