### ISSUE TITLE
Bind ip address

### ISSUE THREAD

**Issue by amandalmia14** [chakki-works/doccano#13]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Python version**: 3.6

How to bind the ip address to 0.0.0.0 such that I call the application remotely within the same private network. 

Thanks

**Comment by alohia** [comment]
`python manage.py runserver 0.0.0.0:<port>`

**Comment by amandalmia14** [comment]
Thanks.
