### ISSUE TITLE
Error reading /home/home/sunyan/doccano/app/server/webpack-stats.json

### ISSUE THREAD

**Issue by SunYanCN** [chakki-works/doccano#138]
![image](https://user-images.githubusercontent.com/42198591/55047373-81c8cd00-507f-11e9-944c-df67e83a3daf.png)

**Comment by Hironsan** [comment]
Please run:

```bash
npm run build
```

or,

```bash
npm start
```

**Comment by vcjob** [comment]
> Please run:
> 
> ```shell
> npm run build
> ```
> 
> or,
> 
> ```shell
> npm start
> ```

Sorry to reply to the closed issue, but just faced with the same one. 
When input npm run build I see 
(venv) root@neuro:/opt/text_annotation_tool/doccano/app# npm run build
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-10T17_39_15_836Z-debug.log
--
That command is executed just fine on the frontend folder only.
Any suggestions?

**Comment by nanjusoil** [comment]
shoud execute the command in app/server/static
not sure what's the difference between static and frontend.
Anyone have any idea?

**Comment by AKhateeb** [comment]
Hi, Did anyone fix the issue, I'm still facing a problem running the local clone of doccano.

I followed all steps described for install requirements of python and npm, and I'm still unable to understand the integration of django part and node.js par.
The Node.js app is running using `npm start` but it looks like static with no ability to save the annotation results.
The Django app is not running at all, it shows an error message:
```
Are you sure webpack has generated the file and the path is correct?
```
Although I have built the entire js packs using `npm run build` and still unable to find the file `webpack-stats.json` that stops the server app!!

Appreciate any help

**Comment by Smyja** [comment]
> Hi, Did anyone fix the issue, I'm still facing a problem running the local clone of doccano.
> 
> I followed all steps described for install requirements of python and npm, and I'm still unable to understand the integration of django part and node.js par.
> The Node.js app is running using `npm start` but it looks like static with no ability to save the annotation results.
> The Django app is not running at all, it shows an error message:
> 
> ```
> Are you sure webpack has generated the file and the path is correct?
> ```
> 
> Although I have built the entire js packs using `npm run build` and still unable to find the file `webpack-stats.json` that stops the server app!!
> 
> Appreciate any help

where you able to find the webpack-stats.json or solve the problem? i am running into the same isssue
