### ISSUE TITLE
Impossible to edit labels for imported data

### ISSUE THREAD

**Issue by guglielmoacabbi** [chakki-works/doccano#140]
Hi,
when I try to load a JSONL data file, a predetermined type of label is preassigned to any label.
For instance the same color (blue) is assigned to any label and it becomes difficult to distinguish them afterwards.
It would be nice to be able to edit the labels after the data is loaded in doccano.
Thanks

**Comment by maneo** [comment]
I am experiencing the same problem. After importing I would like to add keyboard shortcuts.

**Comment by sudodoki** [comment]
Other possible fix might be to use predefined set of sets with color / shortucts, yet it won't work for 100% of use-cases
