### ISSUE TITLE
Not Found: /api/projects/

### ISSUE THREAD

**Issue by DSLituiev** [chakki-works/doccano#149]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX
- **Python version**:  3.6

### Describe the problem
After completing all installation steps, When I go to "Projects" page, I am getting server log:

```
[11/Apr/2019 00:15:17] "GET /projects/ HTTP/1.1" 200 9983
Not Found: /api/projects/
[11/Apr/2019 00:15:18] "GET /api/projects/ HTTP/1.1" 404 5044
```

I try to create a project -- dialog pops up, but "Create" button does not work (even after filling in all fields).

### Source code / logs
```
[11/Apr/2019 00:15:17] "GET /projects/ HTTP/1.1" 200 9983
Not Found: /api/projects/
[11/Apr/2019 00:15:18] "GET /api/projects/ HTTP/1.1" 404 5044
```

**Comment by BrambleXu** [comment]
In our intention, the docker version is for production, and install everything step by step is for development.
So you are trying to build a development version but with error, instead of the production version by docker. Am I right?

**Comment by DSLituiev** [comment]
I am installing it from the master branch, not docker

**Comment by BrambleXu** [comment]
It works well. I can not reproduce the problem. 
Did you run the front server by `npm start`?

**Comment by DSLituiev** [comment]
no, I am going straight to 
```python manage.py migrate
python manage.py createsuperuser
python manage.py runserver
```

when I run `npm start` I see the raw files served. Sorry, I tried something that worked just couple of months ago and now it seemingly breaks. I am sorry if I am misusing github issues, but where can I have most recent dev instructions? I cannot find much on wiki. Thank you

**Comment by BrambleXu** [comment]
Yes, doccaon changed a lot recently. You can find instructions in README.md and follow option 2 to build a development version.
```
Option2: Setup Python environment
```

**Comment by DSLituiev** [comment]
yes yes, I did exactly that. 
I still believe it is a bug.
You can reproduce my error by following these commands in a fresh environment: 

```
conda create -n doccano-fresh python=3.6
. activate doccano-fresh

pip install -r requirements.txt
cd app/server
npm install
npm run build
python manage.py migrate
python manage.py createsuperuser
python manage.py runserver
```
and then the error as described above

**Comment by BrambleXu** [comment]
As I mentioned, you miss `npm start`. Please read the README carefully.
```
# npm start  # for developers
```

**Comment by lapolonio** [comment]
I think new commands are:

```
conda create -n doccano-fresh python=3.6
. activate doccano-fresh

pip install -r requirements.txt
cd app/server/static
npm install
npm run build
cd ../..
python manage.py migrate
python manage.py createsuperuser
python manage.py runserver
npm start  # for developers
```

**Comment by callmeashish** [comment]
OS - Ubuntu 19.10
Python - 3.6
I'm getting an error while running npm build.

Debug log from npm attached.
[npm-debug.log](https://github.com/doccano/doccano/files/4192133/npm-debug.log)
