### ISSUE TITLE
Export sequence labels as document+entities json

### ISSUE THREAD

**Issue by jamesmf** [chakki-works/doccano#15]
### Feature Request
When in a Sequence Labeling project, it would be nice to be able to export the data in a format like [spacy's training](https://spacy.io/usage/training#training-simple-style) format.
```
("Uber blew through $1 million a week", {'entities': [(0, 4, 'ORG')]}),
("Google rebrands its business apps", {'entities': [(0, 6, "ORG")]})
```

### Describe the problem
This feature would make the file we're downloading a lot smaller and also make offline entity labeling pipelines a lot faster.

**Comment by jamesmf** [comment]
I implemented the bare bones of this [here](https://github.com/jamesmf/doccano/pull/1) but it doesn't have a front-end because I'm not sure the best way to do it with a button (prompt?)

It should probably be tied to the code in AutoLabeling.put too.

**Comment by Zerthick** [comment]
If exporting entity annotations in spaCy format is to be supported it would also be useful to be able to export text classifications in a spaCy like format as well such as:

```
("Uber blew through $1 million a week", {'cats': {'BUSINESS': 1.0, 'MONEY': 1.0}}),
("Google rebrands its business apps", {'cats': {'BUSINESS': 1.0, 'MONEY': 0.0}})
```

**Comment by jamesmf** [comment]
This section (in load_data()) suggests that the values should be Boolean (don't know if it matters), but I haven't seen an example of multiple categories. From your example I'm assuming we would want to export every label for every document?

**Comment by Zerthick** [comment]
Yes based on this example: https://github.com/explosion/spacy/blob/master/examples/training/train_textcat.py it appears that the data should be boolean, even though it is given as a digit in the code examples.  Dumping the training dataset to json looks like this: https://gist.github.com/Zerthick/271ff0f2a36898d58da56e1f81e9d3be

Based on this issue https://github.com/explosion/spaCy/issues/2105 I believe spaCy supports multi-label text categorization and as such I assume one would export all possible labels for each sample, with the labels for that particular sample set to true.

**Comment by jamesmf** [comment]
Is it fair for this to be impelemented with "format=spacy" passed to the DataDownload endpoint? In the case of SequenceLabeling, it'd download it as the format in the branch I referenced above, and in the TextCategorization it would export {'cats': {'label_1': True, 'label_2': False', ...., 'label_N': False}}. For Sequence to Sequence, it could ignore it.

**Comment by Zerthick** [comment]
That would seem logical to me, but we'll have to see what @Hironsan thinks.

**Comment by jamesmf** [comment]
I haven't worked any more on it because I don't know how it is best implemented on the front end: should the export data button become a dropdown? 

Also I originally was working off `feature/auto_labeling` so my work can't be cleanly PR'd back into `master`. I don't want to go back and tackle the rest of this feature from `master` until I'm sure I understand how/whether I can get things merged back in.

**Comment by Zerthick** [comment]
I agree, I think guidance from either @Hironsan or @icoxfog417 is needed before moving forward.

**Comment by BrambleXu** [comment]
@jamesmf  We are working to implement a download page with two download buttons. The 'export data' in the navigation bar can redirect the user to download page. A user can choose to download CSV file or JSON file by clicking the button.
