### ISSUE TITLE
classification label import does not work 

### ISSUE THREAD

**Issue by DSLituiev** [chakki-works/doccano#150]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX
- **Python version**: 3.6

### Describe the problem

I am trying to import JSONL:
```
{"text":"Invasive matrix producing carcinoma with focal myxoid and chondroid matrix production, (metaplastic carcinoma) SBR grade","labels":["cancer-metaplastic-invasive"]}
{"text":"Invasive mucinous carcinoma, 1.1 cm, SBR grade","labels":["cancer-mucinous-invasive"]}
``` 
or CSV file:
```
text,labels
"Invasive matrix producing carcinoma with focal myxoid and chondroid matrix production, (metaplastic carcinoma) SBR grade",cancer-metaplastic-invasive
"Invasive mucinous carcinoma, 1.1 cm, SBR grade",cancer-mucinous-invasive
```

In either case, upload does not happen, and I am getting:

```
Bad Request: /v1/projects/1/docs/upload
[11/Apr/2019 01:26:03] "POST /v1/projects/1/docs/upload HTTP/1.1" 400 1805
Bad Request: /v1/projects/1/docs/upload
[11/Apr/2019 01:26:09] "POST /v1/projects/1/docs/upload HTTP/1.1" 400 43
```

**Comment by DSLituiev** [comment]
Additionally for the JSONL format, I am getting:

```
Invalid file format, line 1: u
```

**Comment by icoxfog417** [comment]
Thank you for reporting an issue. Could you please confirm the following checklist?

* File encoding:  `UTF-8` is appropriate.
* File name: alphabetic file name is suitable.
* JSON/JSONL
  * Confirm JSON data is valid. You can use [JSONLint ](https://jsonlint.com/) or some other online tool.
* CSV
  * Confirm CSV data is valid: You can use [gist](https://gist.github.com/) to check it. If your data is valid, CSV file is displayed as formatted.

(You don't need your real & all data to check file. The picked data & masked data is suitable if your data is large or secret.)

**Comment by DSLituiev** [comment]
- File encoding: UTF-8 is appropriate.
  - yes 
- File name: alphabetic file name is suitable.
  - yes, though initially it was alpha-numeric with dashes. making it strictly alphabetic did not solve it
- Confirm JSON data is valid. You can use JSONLint or some other online tool.
  - Json Lint does not work with line-separated JSON, which JSONL is to my understanding, right?  
CSV
- Confirm CSV data is valid: You can use gist to check it. If your data is valid, CSV file is displayed as formatted.
  - I assume you request to upload a file to gist? A head of some 50 lines worked, but more breaks. I cannot upload the whole file due to privacy concern

**Please advise how to turn on the error logging to something more meaningful than "bad request"**

**Comment by DSLituiev** [comment]
So the issue seems to be related to the file being longer than `IMPORT_BATCH_SIZE`.

**Comment by DSLituiev** [comment]
The issue arises after a batch with an empty `{"text":""}` in it is yielded during parsing.

**Comment by icoxfog417** [comment]
doccano does not allow blank data (because you can't annotate to blank data). So please check & exclude blank data.

**Comment by c-w** [comment]
I believe doccano was not correctly displaying the validation errors in this case which may have led to the confusion. I've submitted a PR to fix this: https://github.com/chakki-works/doccano/pull/157.

**Comment by kuraga** [comment]
@c-w but... we have the same for text format (`Invalid format` on blank line).
