### ISSUE TITLE
Add Auditor roles in annotation process with doccano (low priority)

### ISSUE THREAD

**Issue by BrambleXu** [chakki-works/doccano#152]
Right now there are two roles in annotation process with doccano: *Administrator* and *Annotator*. 

It might be good to add an *Auditor* role to check the annotation. This will help to see the quilty of *Annotator*.

A) Annotator: The Annotator is responsible for marking the data.
B) Auditor: The auditor is responsible for reviewing the quality of the marked data.
C) Administrator: Manage personnel, issue tasks, and count wages.

The priority of this feature is not high.

wiki: [Roles in Annotation Process](https://github.com/chakki-works/doccano/wiki/Roles-in-Annotation-Process)

**Comment by Hironsan** [comment]
# Design 1

![image](https://user-images.githubusercontent.com/6737785/56017115-4691f380-5d39-11e9-8bbf-20b7f2e669fc.png)

# Design 2

![image](https://user-images.githubusercontent.com/6737785/56017157-5dd0e100-5d39-11e9-8668-dab86271470a.png)

**Comment by BrambleXu** [comment]
I go with design 1.  
It is more clear to directly incorporate `role_id` in `Member` class. The `MemberRole` class in design 2 is a little redundant.

**Comment by c-w** [comment]
Just as an update: @rbinrais, @fnocera, @margaretmeehan and @armanrahman22 are working on adding a roles system to Doccano as well as a UI/APIs to manage the users and roles on each project.

Tagging @Hironsan and @icoxfog417 for visibility.

**Comment by c-w** [comment]
See https://github.com/chakki-works/doccano/pull/333 for an implementation of RBAC on doccano that introduces three roles:

View ↓ / Role → | Project Admin | Annotator | Annotation Approver
-- | -- | -- | --
Me | x | x | x
Features | x | x | x
ProjectList | x | x | x
ProjectDetail | x | x | x
StatisticsAPI | x | x | x
ApproveLabelsAPI | x |   | x
LabelList | x | x | x
LabelDetail | x | x | x
DocumentList | x | x | x
DocumentDetail | x | x | x
AnnotationList | x | x | x
AnnotationDetail | x | x | x
TextUploadAPI | x |   |  
CloudUploadAPI | x |   |  
TextDownloadAPI | x |

**Comment by c-w** [comment]
@icoxfog417 @Hironsan I believe this was implemented by #333

**Comment by icoxfog417** [comment]
This feature is solved by #333. Thank you for the great work of @margaretmeehan  and @c-w !
