### ISSUE TITLE
Feature Request: Import project-level metadata with JSONL

### ISSUE THREAD

**Issue by DSLituiev** [chakki-works/doccano#154]
Problem: currently there is no way to pre-define labels, their colors in a reproducible way. For projects with some 5 labels it is OK, but for more complex multi-class projects it becomes a limitation. Other project-level settings like user access may be also controlled this way.

Proposed solution: check first line of the JSONL file for presence of a specific key, like "definition", or absence of "text", and if condition is true, treat it as a project definition, and creates labels from it.

Proposed example:

```
{"definition":
     {"labels":
          [{"tag":"dog", "short":"d",  "color": "b"},
           {"tag":"cat", "short":"c", ,  "color": "r"},
           {"tag":"bird", "short":"b", ,  "color": "w", "bgcolor": "k"}
          ],  
      },
     {"users": ["alice", "bob"]}
}
```

Note that it must be a one-liner in actual JSONL

**Comment by BrambleXu** [comment]
Thanks for your proposal. But it needs much effort to pre-define and increases the burden of importing data. 
Actually, @Hironsan already solved this issue with a more dynamic way. I bet you will love it.  
I will keep this open. Stay tuned.

**Comment by icoxfog417** [comment]
Support by #154.
