### ISSUE TITLE
In doccano exported data, only outputs label ids rather than label name? How can we use it for training?

### ISSUE THREAD

**Issue by SuPanther** [chakki-works/doccano#156]
{'id': 2,
  'text': 'this is an apple.',
  'annotations': [{'label': 5,
    'start_offset': 11,
    'end_offset': 15,
    'user': 1},

**Comment by BrambleXu** [comment]
Duplicate https://github.com/chakki-works/doccano/issues/113
This issue would be solved in the future update.

**Comment by natescrape** [comment]
I am having the same issue. I use both the export buttons but they are in the same format. I have tried on mac and windows - the same. I have reinstalled using most up-to-date versio, still nothing changes. Maybe i am missing something?

**Comment by tomnewg** [comment]
I have the same issue. However, you can export the label data as json and then just map the label id with the label text when preparing the data for training.
