### ISSUE TITLE
Cannot use the same shortcut and label name in different projects

### ISSUE THREAD

**Issue by azar923** [chakki-works/doccano#162]
The issue is the following:

1. I create Project A.
2. Import some annotated data to the project - set of labels is automatically created as a result (let's say, Label 1, Label 2, Label 3)
3. I edit these labels - provide a shortcut and color
4. I create Project B and import another portion of dataset (with the same set of labels)
5. I try to replicate setting of Project A (assign the same shortcuts, colors and label names to labels), which gives me an error:
`You cannot use same label name or shortcut key.`

It seems not very convenient that we cannot create labels with the same shortcut and label name in different project. I wonder if it was made intentionally or it is a bug.

Thank you very much for a great tool.

**Comment by Hironsan** [comment]
Thanks! I will check the problem.

**Comment by Hironsan** [comment]
Problem fixed.

**Comment by azar923** [comment]
Hi @Hironsan 
This issue seems to be fixed, but I now cannot edit label in the same project (receiving "You cannot use same label name or shortcut key." message). Could you please check when you have an opportunity ? Please let me know if we need a separate issue for that.

Thanks.
