### ISSUE TITLE
Label ordering and label metadata in Sequence Labeling

### ISSUE THREAD

**Issue by prokotg** [chakki-works/doccano#164]
Hi there!

First of all, thank you all for contributing to this tool! It's amazing!

I just have one problem, namely, when I export the annotated data I have id of labels that I think are internal for doccano. Unfortunately, it might be the case that if you edit your labels (either change their names or delete and add new) you can end up with ids like 4, 7, 13 even though you have only 3 labels in whole project. In the end I have no idea what 4, 7 and 13 stands for. Would you consider keeping numerical order (1, 2, 3.. or 0, 1, 2...) and exporting labels metadata for example in format {1: "firstlabel", 2: "secondlabel", ...} ? It would be great for post-processing the annotated data. 

Thanks!

**Comment by Hironsan** [comment]
If you are superuser, you can get label metadata by accessing <http://[YOUR_IP]/v1/projects/1/labels> .

![image](https://user-images.githubusercontent.com/6737785/56212709-88060400-6095-11e9-8521-e702e3b114fb.png)

**Comment by prokotg** [comment]
That's helpful for now, thank you! Personally, I would not go for changing id to text. I find ids  + their metadata much more comfortable to work with. Just slipping my humble opinion

**Comment by Hironsan** [comment]
Thanks for your opinion!
