### ISSUE TITLE
"This field may not be blank." when uploading a txt file

### ISSUE THREAD

**Issue by Jsevillamol** [chakki-works/doccano#168]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Python version**: 3.7

### Describe the problem
I followed the steps in the README to launch a local server.

After creating a project for Sequence labelling, I cannot upload the txt file I wanted.

Instead, after selecting the file I want to upload I get the error "This field may not be blank."

![image](https://user-images.githubusercontent.com/5825805/56501108-dee46100-650d-11e9-8554-0dcab77400b4.png)

What is going on? How do I fix it?

**Comment by c-w** [comment]
I've seen this behavior in the past when there were empty lines in the uploaded file. Could you verify that the file doesn't contain any empty of blank lines?

@Hironsan Shall we modify the behavior of the plain text parser to ignore empty lines by default to reduce potential user frustration? This would be quite a simple change:

```patch
diff --git a/app/server/utils.py b/app/server/utils.py
index 439cc87..93a293a 100644
--- a/app/server/utils.py
+++ b/app/server/utils.py
@@ -345,7 +345,8 @@ class PlainTextParser(FileParser):
             batch = list(itertools.islice(file, IMPORT_BATCH_SIZE))
             if not batch:
                 break
-            yield [{'text': line.strip()} for line in batch]
+            lines = [line.strip() for line in batch]
+            yield [{'text': line} for line in lines if line]
 
 
 class CSVParser(FileParser):
```

**Comment by Jsevillamol** [comment]
Yeah, that was the cause of the error indeed! Thank you

**Comment by phoerious** [comment]
The same issue applies to JSON imports. I had add a check to skip all lines with empty text key.
This check should either be added to all importers or empty text fields should simply be permitted as they do no harm.
