### ISSUE TITLE
The external_id can't be found from "meta" in the export format.

### ISSUE THREAD

**Issue by Alvinlift** [chakki-works/doccano#169]
Hello,

my import json format:
{"text": "EU rejects German call to boycott British lamb.", "external_id": 1}

my export json format:
{"id": 2992, "text": "EU rejects German call to boycott British lamb.", "annotations": [{"label": 603, "user": 1}], "meta": {}}

I expect the "external_id" in "meta" of the export json.
I noticed there is this feature merged. Why it isn't in the latest master branch?

Thanks.

**Comment by BrambleXu** [comment]
You should take a look at the example format, `"external_id": 1` should in the `meta` key for the [import format](https://github.com/chakki-works/doccano/blob/66c9221f2bc10526f88091ac137215648a08d5cc/app/server/tests/data/classification.jsonl)

**Comment by Alvinlift** [comment]
Perfect. It works. Thanks for your help.
