### ISSUE TITLE
Render line breaks in sequence labelling task

### ISSUE THREAD

**Issue by phoerious** [chakki-works/doccano#171]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **Python version**: 3.6/3.7

### Describe the problem
White space is visually collapsed in samples of the sequence labelling task by use of `white-space: normal`, whereas all other tasks have `white-space: pre-wrap`.

This makes it virtually impossible to annotate anything that is not a single sentence. Since short sequences tend to not contain many line breaks anyway (and even if they did, it wouldn't hurt), but line breaks are required for annotating longer texts, I suggest using `pre-wrap` for all labelling tasks. Right now, the interface is only useful for annotating individual words in shorter sequences.

**Comment by icoxfog417** [comment]
It is related to #27. In the sequence labeling task, line breaks make defining character position difficult.
