### ISSUE TITLE
"Completed" lists samples multiple times

### ISSUE THREAD

**Issue by phoerious** [chakki-works/doccano#172]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux, Ubuntu 18.10
- **Python version**: 3.7

### Describe the problem
When I browse the data set and filter by "Completed", I get the same instances multiple times in a row (usually 2-3 times). This makes it very annoying to revisit already labelled instances.

### Source code / logs
n/a

**Comment by c-w** [comment]
I can confirm this behavior.

For example, in this screenshot we can see an estimated 13,982 results:

![Screenshot without completed filter](https://user-images.githubusercontent.com/1086421/57636952-39eefe00-7578-11e9-9afc-68b975c4cb74.png)

When adding the completed filter, the number _increases_ to 23,366 results and some items show up duplicated:

![Screenshot with completed filter](https://user-images.githubusercontent.com/1086421/57637028-6440bb80-7578-11e9-8e54-ef99bc2445ca.png)
