### ISSUE TITLE
Restore old color palette to pick label colors

### ISSUE THREAD

**Issue by azar923** [chakki-works/doccano#175]
Hello,

Some time ago it was a nice way to choose color for labels (palette). It was very fast and easy to use. Recently it was changed to button-based way and, from my perspective, it makes project configuration much less convenient. When there are a lot of labels in project (especially in sequence labeling), it is necessary to tune colors carefully, which is very hard to do with new version. 
Could you please add an additional way to pick color (with color palette, as before) ?

**Comment by Hironsan** [comment]
OK.
