### ISSUE TITLE
How to create an annotator role

### ISSUE THREAD

**Issue by Alvinlift** [chakki-works/doccano#177]
Hello,

I follow the readme to create an admin role.

docker exec doccano tools/create-admin.sh "admin" "admin@example.com" "password"

But How do I create a regular annotator role?

Btw, when I am in "Create Project", why I can't see the User list?

Thanks.

**Comment by Alvinlift** [comment]
Hello,

I follow the readme to create an admin role.

docker exec doccano tools/create-admin.sh "admin" "admin@example.com" "password"

But How do I create a regular annotator role?

Thanks.

**Comment by icoxfog417** [comment]
You can create other annotators by [Django Admin site](https://djangobook.com/django-admin-site/).
