### ISSUE TITLE
How to persist results in database(postgres)?

### ISSUE THREAD

**Issue by Alvinlift** [chakki-works/doccano#179]
Right now, we download the annotation result as a file.
1. Where can I find the annotation result stored in Docker?
2. Could we config database, so the result will be auto persisted into DB?
I just don't want once Docker container is removed. The annotation result is gone.
Thanks.

**Comment by icoxfog417** [comment]
It totally depends on your `docker run` configuration. [You have to specify volume to persist your database](https://docs.docker.com/storage/volumes/).
