### ISSUE TITLE
ERROR after login

### ISSUE THREAD

**Issue by jmlongriver** [chakki-works/doccano#186]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: mac 10.13.6
- **Python version**: Python 3.6.0

### Describe the problem
GET /api/projects/ HTTP/1.1" 404 when login into the project, no "create" button showed

**Comment by Hironsan** [comment]
Did you install npm packages and run `npm start` command?

**Comment by icoxfog417** [comment]
Please raise a new issue if you still face this phenomenon.
