### ISSUE TITLE
Importing data does not set annotated labels

### ISSUE THREAD

**Issue by wouterMostard** [chakki-works/doccano#187]
Hello all,

Importing an annotated data set in a new project does not set the labels specified in the JSON. We tested this by making a new project, adding one annotation to one file and exporting it. 

Then, we made a new project, added the correct label and imported the data. The text is now visible for annotating but no previous annotations are visible. They are visible in the JSON.

update: The problem arises because because the annotations are placed under the key "annotations" when exporting the data. During import the key "labels" is used for finding the previously exported annotations. 

Wouter

**Comment by maneo** [comment]
The input and output format is different check out [this](https://github.com/chakki-works/doccano/wiki/Import-and-Export-File-Formats). It is a pity that you cannot import output of the export, but it is pretty straightforward to write converter e.g.

`import json
import sys

# Input:
# {"id": 1, "text": "EU rejects ...", "annotations": [{"id": 1, "label": 2, "start_offset": 0, "end_offset": 2, "user": 1}]}
# {"id": 2, "text": "Peter Blackburn", "annotations": [{"id": 2, "label": 1, "start_offset": 0, "end_offset": 15, "user": 1}]}
# {"id": 3, "text": "President Obama", "annotations": [{"id": 3, "label": 1, "start_offset": 10, "end_offset": 15, "user": 1}]}

# Output:
# {"text": "EU rejects German call to boycott British lamb.", "labels": [ [0, 2, "ORG"], [11, 17, "MISC"] ]}
# {"text": "Peter Blackburn", "labels": [ [0, 15, "PERSON"] ]}
# {"text": "President Obama", "labels": [ [10, 15, "PERSON"] ]}
#

labels_dict = {"2": "ORG",
               "3": "MISC",
               "4": "PERSON"}

for document in sys.stdin:
    json_doc = json.loads(document)

    converted_doc = dict()
    converted_doc["text"] = json_doc["text"]

    labels = []
    annotations = json_doc["annotations"]

    for annotation in annotations:
        start_offset = annotation["start_offset"]
        end_offset = annotation["end_offset"]
        label = labels_dict[str(annotation["label"])]

        new_labels = list()
        new_labels.append(start_offset)
        new_labels.append(end_offset)
        new_labels.append(label)

        labels.append(new_labels)

    converted_doc["labels"] = labels
    print(json.dumps(converted_doc))
`

**Comment by c-w** [comment]
This should have been fixed by https://github.com/chakki-works/doccano/pull/217 which introduces a new format where the exported values can directly be re-imported.
