### ISSUE TITLE
AWS CloudFormation: ImageId does not exist

### ISSUE THREAD

**Issue by JMuscatello** [chakki-works/doccano#190]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: any
- **Python version**: any

### Describe the problem
I can't create an aws CloudFormation stack from the template since the ImageId does not exist.

### Source code / logs
The image id '[ami-0ac019f4fcb7cb7e6]' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidAMIID.NotFound; Request ID: 5310f864-f225-44c3-ae1e-d24ba7269474)

**Comment by BrambleXu** [comment]
It is weird. I test the launch button and it works fine. The possible reason is that you may change the region from `US East (N. Virginia)` to other places. Please give me more information.

**Comment by JMuscatello** [comment]
Yes that was the problem, I was trying to run it from a different region. Many thanks!
