### ISSUE TITLE
There are not field `Users` when creating project.

### ISSUE THREAD

**Issue by SlonSky** [chakki-works/doccano#198]
Runned doccano with docker, created admin. When creating a new projects, i see form with no field for users selection for this project.
![image](https://user-images.githubusercontent.com/16941707/57698031-3f724400-765d-11e9-9bc7-9bc5826e4bc8.png)

This form differentiates from images in README.md:
![image](https://user-images.githubusercontent.com/16941707/57698104-70eb0f80-765d-11e9-9ec9-b06b7675c607.png)

Made no changes, just pulled and run.
Is it expected behaviour and we need now to manage all users and attach them to projects only via django admin ?

**Comment by icoxfog417** [comment]
Now we are implementing user administration feature to assign the member to project.  Until this done, please use Django admin page to assign member :pray:
