### ISSUE TITLE
No way to add users to an existing project

### ISSUE THREAD

**Issue by olix20** [chakki-works/doccano#2]
Thanks @Hironsan for this usefull repo. 
I can't seem to find a way to add new users to an existing project form the dashboard. 
If there's a quick way to do it programmatically pls let me know.

Other nice to have's:
- ui for creating new users, or instruction how to do it from shell 
- always add superuser as a user when creating a project

**Comment by icoxfog417** [comment]
Thank you for trying to use the doccano!

Now doccano does not have the feature to add the user. You can use Django  administrator page to create new users.

[Django admin](https://tutorial.djangogirls.org/en/django_admin/).

**Comment by olix20** [comment]
thanks @icoxfog417.  right, i can create new django users, that's no problem.
the problem is that you can only add users to projects when you're creating the project. there's no way to add/remove users to project after it's created.

**Comment by icoxfog417** [comment]
Exactly, you can select the users of a project only when creating it. After you create the project, you have to use Django administrator page to manage users.

* Creating and managing the users of a project
  * Django Admin page
* Assign the users to project when creating it
  * You can do it on doccano

**Comment by PavelKovalets** [comment]
We should add this info somewhere in the documentation

**Comment by svenvanderburg** [comment]
@icoxfog417 Can you explain in more detail how to add more users to a project? I can indeed add new users through the Django Admin page. But I cannot assign these users to projects. The only way to have a user access a project seems to be to create that project as that user.

**Comment by rbagd** [comment]
@svenvanderburg When you open the project you created in Django Admin itself, you can multi-select the users that can access it.

**Comment by svenvanderburg** [comment]
@rbagd I tried that, but the users listed in the project don't actually have access to the project. Even if I add another user within a project, that user does not have access to it. Do I need to manually assign specific permissions for each user? And which ones?

**Comment by rbagd** [comment]
Usually, I put all users in a single group and give the group permissions only for the appropriate type of annotations they could do, e.g. `server / document annotation / {change, delete, add, view}`. I never experienced any issues with this way of doing things.

**Comment by svenvanderburg** [comment]
I tried assigning a user to a group and give that group the permissions you suggested, but it still does not work. Even if I give a user all possible permissions and add it to the project, it can not view the project if it has been created by a different user.

**Comment by rbagd** [comment]
@svenvanderburg Can you make sure the users you have added appear indeed in the user list when you do a `GET` request to `$BASE_URL/v1/projects/$PROJECT_ID`?

**Comment by svenvanderburg** [comment]
Yep, all users added show up in the 'users' list in the project detail page.

**Comment by gabrer** [comment]
I have experienced the same issue and I've noticed that if the project has been created once the users already existed, they are then able to see it.
