### ISSUE TITLE
Randomness in document ordering

### ISSUE THREAD

**Issue by rbagd** [chakki-works/doccano#201]
I am trying to introduce some randomness into the order with which documents are presented to the user for annotating. My simple solution is changing line 110 in `app/server/api.py` to

````
class DocumentList(generics.ListCreateAPIView):
    queryset = Document.objects.all().order_by('?')
````

However, doing it this way removes the expected behaviour of `Prev / Next` buttons as paginated lists get refreshed each time, so I am wondering if there's a smarter way to go about this that could keep at least `Prev / Next`.

I am essentially trying to find a quick workaround for https://github.com/chakki-works/doccano/issues/20 within current code base.

**Comment by BrambleXu** [comment]
It might be good to provide options for normal mode and random mode when starting the annotation project.

**Comment by c-w** [comment]
Currently the project uses the offset-based pagination from django-rest-framework ([implementation code](https://github.com/encode/django-rest-framework/blob/db37512a6e4fa5ba793b7e401d7014dfd0984995/rest_framework/pagination.py#L334)). A very simple way of adding some pseudo-random document order could be to make the pagination wrap-around (so we extend `LimitOffsetPagination.get_offset` and set `offset = offset % count`) and then start each user at a different starting offset. This doesn't randomize the document order entirely, but for large collections of documents may still work towards reducing annotation fatigue. Thoughts?

**Comment by rbagd** [comment]
The one unintended consequence that I see now is that progress bar in the annotation screen is probably going to get more confusing. Since users would start with annotating different parts of the dataset and progress is measured project-wise, it will get filled pretty fast. It would probably more clear if it could reflected the progress of the user only but that's a separate issue.

**Comment by c-w** [comment]
@rbagd Looks like a per-user progress bar has been merged in https://github.com/chakki-works/doccano/pull/230.
