### ISSUE TITLE
Collaborative annotating and Custom Json data structure

### ISSUE THREAD

**Issue by JordanSimba** [chakki-works/doccano#209]
I was wondering how the tool actually handles collaborative annotating, how will the labels be attributed to all annotators?
How does one invite and control permissions of a collaborator?

Would it be possible allow the user to choose the field of text to render in the input json data structure (as would be in input jsonL file)?

Is it possible to add multiple annotations to one utterance/ or one phrase?

**Comment by BrambleXu** [comment]
> I was wondering how the tool actually handles collaborative annotating, how will the labels be attributed to all annotators?
One can create an annotation project and annotators can do their work for this project.

> How does one invite and control permissions of a collaborator?
[Frequently Asked Questions](https://github.com/chakki-works/doccano/wiki/Frequently-Asked-Questions)

> Would it be possible allow the user to choose the field of text to render in the input json data structure (as would be in input jsonL file)?
Right now this is impossible. 

> Is it possible to add multiple annotations to one utterance/ or one phrase?
You can not annotate an utterance multiple times.
