### ISSUE TITLE
Feature Request: Delete this document

### ISSUE THREAD

**Issue by jamesmf** [chakki-works/doccano#21]
### Describe the problem
It would be very useful to be able to delete a document from its annotation page. This would be great for datasets where you haven't/can't do robust validation before uploading. 

### Source code / logs
I assume this is more complicated than a DELETE to the Document endpoint, but I'm not sure. It might make sense if this was an admin-only button, but I could see a use case where part of an annotator's job was to clean the dataset.

**Comment by cathalgarvey** [comment]
I'd also like to see this, for either site or project admins, or configurably for all users of a project.

I just uploaded a test sequence for a labelling project, and realised I can't get rid of the test sequence, now. Thankfully it's kinda usable.. but still, would be good to address this.

**Comment by john-dugan** [comment]
As a workaround for now, I was able to delete documents from the Django admin site /admin/server/document/

**Comment by c-w** [comment]
@jamesmf @jamesmf @john-dugan The delete feature is now implemented and available to admins on the dataset page.
