### ISSUE TITLE
CoNLL data import selects only the first 500 sentences

### ISSUE THREAD

**Issue by olix20** [chakki-works/doccano#218]
### System information
- **OS Platform and Distribution**: MacOS 10.14.5
- **Python version**: 3.7

### Describe the problem

For a NER problem i'd like to import data in CoNLL format. I have around 1000 sentences in my file. When I try to import it, it takes only the first 500 sentences (100 pages after import) and the rest are gone. This looks like a **bug**. 

The only way to work around it is to split the input and import consequitively in batches of 500 sentences.

**Comment by c-w** [comment]
The data import pagination code wasn't covered in the unit tests so I made a change to ensure those code paths are exercised during the CI (see https://github.com/chakki-works/doccano/pull/223). However, I can't reproduce the behavior. Would it be possible for you to share a sample data file for which you see the bug?

**Comment by olix20** [comment]
i see if i can make a sample conll file. when i increase `IMPORT_BATCH_SIZE` to 1500, nothing gets imported without any errors in the console or terminal. @c-w

**Comment by c-w** [comment]
@olix20 Thanks for that information. The behavior you reported leads me to the hypothesis that your file may have trailing newlines which leads doccano to silently skip the import of the data. Please let me know if removing any trailing newlines from your file fixes the import. I've also made a pull request to fix this behavior (see https://github.com/chakki-works/doccano/pull/225).

**Comment by olix20** [comment]
Yes indeed the file had two new line characters at the end. Removing one solves the problem. Thanks @c-w !
