### ISSUE TITLE
upload txt for document classification

### ISSUE THREAD

**Issue by bifeng** [chakki-works/doccano#22]
1, what's the format of txt files?
2, after upload the dataset, but can't find it in this project.

any suggestion?

Thank you for this beautiful tools!

**Comment by bifeng** [comment]
yes, i did exact what you said. I create a classification project. In this txt, each row is a sentence, but when upload this dataset, didn't show  this data for labeling,

**Comment by icoxfog417** [comment]
Thank you for letting me know the phenomenon. Could you provide your uploaded file information?

* file encoding
* number of line count
* line separator (`crlf` or `lf`)
* language (English, Chinese etc)

And please show us some lines of your text file like following if you could.

```
this movie is awesome
the performance of some actors  was terrible
....
```

**Comment by bifeng** [comment]
Yes, this is my test files:
[test.txt](https://github.com/chakki-works/doccano/files/2512949/test.txt)

**Comment by icoxfog417** [comment]
Thank you for the file. Please try upload after following 2 operation.

* Convert file encoding to UTF-8.
  * doccano allows UTF-8 encoded file. Your file encoding seems to be GB 2312.
* Delete blank lines
  * Your file includes blank line. so please delete these because each line should have data.

**Comment by bifeng** [comment]
thanks!

**Comment by professorlust** [comment]
Duplicate of #22

Each time I attempt to upload this file on my local machine I get the error "something went wrong"

Any ideas as to why its not being accepted?

[Test1.txt](https://github.com/chakki-works/doccano/files/2854580/Test1.txt)

**Comment by Hironsan** [comment]
I confirmed your file. Its encoding is UTF-16.

```
> nkf -g Test1.txt
UTF-16
```

Try to convert UTF-8 from UTF-16. It works fine.

```
> nkf -w Test1.txt > Test2.txt
```
