### ISSUE TITLE
How to import extra metadata

### ISSUE THREAD

**Issue by Tideass** [chakki-works/doccano#220]
Hello,

Is there anyway to import in additional metadata besides the text? I've created 2 columns in my import csv. One called text and one called metadata. The text has the text, but the metadata is an ID. What I wanted to do was to assign human in the loop to each text based on the ID they have. 

IS ti possible to do something like this with Doccano at the moment?

**Comment by icoxfog417** [comment]
You can import metadata by using JSON format. Please refer following document.

https://github.com/chakki-works/doccano/wiki/Import-and-Export-File-Formats#import-format

**Comment by travishsu** [comment]
Hi @icoxfog417, I've encountered a similar issue, but the link has expired. Could you update the page on your [documentation website](https://doccano.github.io/doccano/)?

Many thx!

**Comment by icoxfog417** [comment]
Dear @travishsu , thank you for using the doccano! There is not detail documentation but we prepare the following section to learn how to upload dataset.

https://doccano.github.io/doccano/tutorial/#import-a-dataset

**Comment by leweex95** [comment]
@icoxfog417, so how is it possible to import additional metadata with an input file? I would at least want to attach the filename and the entities to be labeled alongside the imported text file, but the documentation still doens't say anything about this feature.

**Comment by ltiAlan** [comment]
I found that it is possible to add metadata when you import data using JSONL format. How to do it can be seen in the following question:

https://github.com/doccano/doccano/discussions/1483

Although they are asking a different question about linking the file name, their example shows how they added the meta data by simply adding additional attributes to their JSONL data. For example:

{"text": "This is my text string to be annotated", "labels": [], "Id": "12345", "filename": "original_file.pdf"}

This would provide both the id and filename metadata associated with that text string.
