### ISSUE TITLE
[feature request] Add customize font functions or change web-ui's font-family

### ISSUE THREAD

**Issue by BrikerMan** [chakki-works/doccano#226]
If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Docker Version

### Describe the problem

Current version's css show Chinse characters very unfriendly.

![7B76FAE7-AE1E-444A-AE0A-52E907C92240](https://user-images.githubusercontent.com/9368907/58537186-f60d2180-8224-11e9-9382-0c58e2e85004.png)

**Comment by BrambleXu** [comment]
It seems the font family cannot render some specific Chinse characters, for example, the character "门". 

![image](https://user-images.githubusercontent.com/10768193/58542748-1515ae80-8239-11e9-96a4-f34c845c48b2.png)
(this looks not bad)

![image](https://user-images.githubusercontent.com/10768193/58542778-2494f780-8239-11e9-98ad-bd0d7586e5a6.png)
(character "门")
