### ISSUE TITLE
website login

### ISSUE THREAD

**Issue by shahmohamadi** [chakki-works/doccano#227]
how can I login in website? http://doccano.herokuapp.com/
and how can I use team working? could I install source could on my own server or is there other ways?

**Comment by c-w** [comment]
There are many ways in which you can deploy your own copy of the app, including [Azure](https://github.com/chakki-works/doccano#azure), [Heroku](https://github.com/chakki-works/doccano#heroku) and [AWS](https://github.com/chakki-works/doccano#aws). You can also run the [Docker container](https://hub.docker.com/r/chakkiworks/doccano) on your own server.

**Comment by icoxfog417** [comment]
http://doccano.herokuapp.com/ is demo site. So you can't login it.
You have to deploy your doccano to Heroku if you want login & use.
