### ISSUE TITLE
Use doccano without internet connection

### ISSUE THREAD

**Issue by aurelien-clu** [chakki-works/doccano#23]
The project does not work without internet connection.
Is it possible to have an argument so the project works offline?
Or is the code easily editable for that purpose?

Note:
I have not checked the source code yet.

### System information
- **Debian GNU/Linux 9.5**:
- **Python 3.6.7 :: Anaconda, Inc.**: 
- **Mozilla Firefox 60.3.0**
- **Chromium 69.0.3497.92 built on Debian 9.5, running on Debian 9.5**

#### Internet connection `on`
The project works fine with `Firefox` and with `Chromium`.

#### Internet connection `off`
The project does not work any longer with `Firefox` and with `Chromium`.

According to your `README.md`, requirements are:
- Python 3.6+
- django 2.0.5+
- Google Chrome

Since this uses supposedly only Python, I don't see any reason why the project should target:
- unpkg.com
- cloudflare

while it is open in browser.

### Source code / logs

I don't think logs will give any insight but just in case, here they are.

**Comment by jamesmf** [comment]
I agree that it'd be great if the installation step grabbed those dependencies. I think running this locally is a valid use case, and it would be nice not to have to hit a CDN

**Comment by icoxfog417** [comment]
We use internet connection (access to CDN) to avoid including external JavaScript/CSS file in this repository.

You can use doccano offline by downloading CDN hosted files and edit link. But we don't have any plan to support offline usage now (because you need an internet connection to install the doccano).

**Comment by icoxfog417** [comment]
It'll be possible but does not change the fact that requires an internet connection when installing doccano.

**Comment by jamesmf** [comment]
That makes sense. I could imagine the use case where someone installs with internet, but wants to be able to annotate locally without internet. But seems like a low priority feature

**Comment by icoxfog417** [comment]
Yes, we are totally the same opinion as you.

**Comment by aurelien-clu** [comment]
Yeah that's what I did ;)

Here is a quick security check from a random guy written in `Markdown` (`.txt` since Github refuses me to attach a `.md`)
[security_check.txt](https://github.com/chakki-works/doccano/files/2518781/security_check.txt)

ps: No bad feeling but I don't know you enough to trust you with my data or data that I don't own ;)
