### ISSUE TITLE
After adding users in Django Admin, still there are no field `Users` when creating project

### ISSUE THREAD

**Issue by zhangxieyang2** [chakki-works/doccano#231]
### System information
- **Linux Ubuntu 14.04**:
- **Python version 3.6**: 
- **Nodejs v8.16.0**
- **Django 2.1.7**
- **Browser: Chrome**

### Describe the problem
I add a user and a group in Django Admin. The group is assigned with the following permissions.
![image](https://user-images.githubusercontent.com/9495933/58867447-0887cf00-86ed-11e9-82fe-753aea43b546.png)
Then the user is added to this group.
However, when I login with **admin** user and create a new project, I can't see the **User** sub panel.
The problem is similar with [issue#198](https://github.com/chakki-works/doccano/issues/198) **except that I have already create a user and assign corresponding permissions** to him.

### Source code / logs
Besides, when I do a GET request to $BASE_URL/v1/projects/$PROJECT_ID, I can see the added users as the following image shows
![image](https://user-images.githubusercontent.com/9495933/58872705-370aa780-86f7-11e9-8bdf-6301b4132c07.png)

Thank you for your tips in advance !

**Comment by rbagd** [comment]
Make sure to use `Ctrl`, multi-select users that will have access to the project and then save the configuration.

![users](https://user-images.githubusercontent.com/1479558/58874924-6a830d00-86ca-11e9-90cd-a15704aeaabc.png)

**Comment by gabrer** [comment]
> Make sure to use `Ctrl`, multi-select users that will have access to the project and then save the configuration.
> 
> ![users](https://user-images.githubusercontent.com/1479558/58874924-6a830d00-86ca-11e9-90cd-a15704aeaabc.png)

Thank you for pointing this out!
I know that is written under the box, but this kind of UX was very unintuitive for me. 
I would have expected something similar to the way permissions are associated to users, e.g. with two boxes where you can move the options from the left to right box.

**Comment by c-w** [comment]
Note that pull request https://github.com/chakki-works/doccano/pull/333 introduces RBAC which removes the need to use the Django admin to assign users to projects: there is now a tab for each project where new users can be assigned to projects and their access level for the project can be set (e.g. project admin, annotation approver, labeler).

**Comment by icoxfog417** [comment]
This is the Django Admin issue that not related to doccano.
