### ISSUE TITLE
how to label for sentence pairs?

### ISSUE THREAD

**Issue by bifeng** [chakki-works/doccano#24]
For the semantic similarity of two sentence.  Is there any possible to label sentence pairs？
Using '，' to separate two sentence seems possible, but it not very beautiful. How to using two line to show the sentence ?

**Comment by icoxfog417** [comment]
At this time, doccano does not support the labeling between two (or multiple) document. So one of the way to annotate is separating sentence by some separator as you supposed. It would be a little better if we could use line change by #17.

**Comment by icoxfog417** [comment]
#17 is closed and it enables linebreak in document.
