### ISSUE TITLE
how to get the real label name instead of the label id after export the dataset? 

### ISSUE THREAD

**Issue by littleji** [chakki-works/doccano#240]
### Describe the problem
after export the labeled dataset, like this
{"id": 12881, "text": "some text ", "annotations": [{"label": 3225, "user": 1}], "meta": {}}
how can I get the label-id:label-name map to identify the label name?

**Comment by rbagd** [comment]
@littleji, instead of exporting data manually, I just find it easier to connect to the backend database and query it instead with Python or something else. For example, this query to get retrieve all annotations works for SQLite backend (`change your project_id`):

```
SELECT
    doc.id AS document_id,
    doc.text AS text,
    annotation.user_id AS user_id,
    label.text AS label,
    doc.project_id AS project
FROM (SELECT id, document_id, label_id, user_id
      FROM server_documentannotation) AS annotation
INNER JOIN (SELECT id, text, meta, project_id
            FROM server_document
            WHERE project_id = 1) AS doc
    ON annotation.document_id = doc.id
INNER JOIN (SELECT id, text FROM server_label) AS label
    ON annotation.label_id = label.id
```

**Comment by littleji** [comment]
> @littleji, instead of exporting data manually, I just find it easier to connect to the backend database and query it directly with Python or something else. For example, this query to retrieve all annotations works for SQLite backend (change your `project_id`):
> 
> ```
> SELECT
>     doc.id AS document_id,
>     doc.text AS text,
>     annotation.user_id AS user_id,
>     label.text AS label,
>     doc.project_id AS project
> FROM (SELECT id, document_id, label_id, user_id
>       FROM server_documentannotation) AS annotation
> INNER JOIN (SELECT id, text, meta, project_id
>             FROM server_document
>             WHERE project_id = 1) AS doc
>     ON annotation.document_id = doc.id
> INNER JOIN (SELECT id, text FROM server_label) AS label
>     ON annotation.label_id = label.id
> ```

@rbagd thanks for your help! :) but I deployed this project with the old docker way(cause the latest version has some problem with my server), you know how to connect the DB in the docker container?

**Comment by rbagd** [comment]
I guess you could simply just copy the DB file out of the container and use it locally. Does this work?

```
docker cp $CONTAINER_ID:/doccano/app/db.sqlite3 .
```

**Comment by Hironsan** [comment]
After https://github.com/chakki-works/doccano/pull/217, we can access label name instead of label id. Please update.
