### ISSUE TITLE
Timeout on Export 

### ISSUE THREAD

**Issue by gustave-ducrest** [chakki-works/doccano#241]
If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**: 

### Describe the problem
I tried exporting my data (~1600 labelled sequences) out of a much larger data set, but the system timed out. Has anyone determined the limit we can upload/export before the system times out?  

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by Hironsan** [comment]
I have no idea about your environment. But if you are using docker, the timeout is determined by `timeout` parameter in [run.sh](https://github.com/chakki-works/doccano/blob/master/tools/run.sh).

**Comment by john-dugan** [comment]
I've got a heroku deployment running with a project that has ~8000 classification documents that I'm trying to export as well. It's throwing a "Request timeout" / status 503  for  path="/v1/projects/1/docs/download?q=csv"  with the timeout at 30001ms.  It looks like Heroku sets a pretty hard cap on 30 seconds per request https://devcenter.heroku.com/articles/request-timeout

**Comment by c-w** [comment]
@Hironsan Do we want to offload the data export to a queue like Celery? For example, we could use an approach like this:

![Asynchronous data export approach](https://user-images.githubusercontent.com/1086421/60603956-b6d27300-9d84-11e9-9699-7dc425cd7bdb.png)

**Comment by echan00** [comment]
Also having trouble importing/exporting data due to timeout on Heroku.  I can get around the issue with importing by breaking up my data into multiple files, but can't export.

I'm not familiar with vue or django, if no one comes up with a solution I may have to find a way to export the data directly from postgresql

**Comment by john-dugan** [comment]
@echan00 Yep I ended up just exporting from postgresql, but I also might try temporarily bumping the Heroku dyno up a tier or two just to see if the more powerful ones can complete the export in time.

**Comment by echan00** [comment]
@john-dugan thanks would you mind sharing your postgresql export code?

**Comment by john-dugan** [comment]
Sure thing - it by no means was meant to resemble the Doccano export format, just something hacked together that was usable for my case (on the older schema fyi) 

```
SELECT annotation.id, annotation.document_id, annotation.label_id, annotation.user_id, documents.id, documents.text, documents.meta FROM server_documentannotation annotation    INNER JOIN server_document documents ON annotation.document_id = documents.id WHERE annotation.label_id in (3,4,5) ORDER BY documents.id ASC
```

**Comment by echan00** [comment]
Thanks! Exactly what I needed

**Comment by PeterPanUnderhill** [comment]
> Sure thing - it by no means was meant to resemble the Doccano export format, just something hacked together that was usable for my case (on the older schema fyi)
> 
> ```
> SELECT annotation.id, annotation.document_id, annotation.label_id, annotation.user_id, documents.id, documents.text, documents.meta FROM server_documentannotation annotation    INNER JOIN server_document documents ON annotation.document_id = documents.id WHERE annotation.label_id in (3,4,5) ORDER BY documents.id ASC
> ```

I wonder where and how should I execute this SQL command?
