### ISSUE TITLE
Can user A see user B's annotations?

### ISSUE THREAD

**Issue by zhangxieyang2** [chakki-works/doccano#242]
We now have a demo annotation project, and hope that every member can see the example annotation results **using his/her own account (instead of logging in with a public test account)**. Is it possible to do so?
Thank you for any suggestions!

**Comment by atraining** [comment]
Users in one project see only their own Annotations: 

See

https://github.com/chakki-works/doccano/blob/f9be910884b8bbfe4865bee5c3d3df1f5878bd0f/app/server/api.py#L166

**Comment by hkaraoguz** [comment]
Hello @zhangxieyang2. For sequence annotations, I have modified the source code to be able to view the annotations from multiple users. Here is the branch https://github.com/hkaraoguz/doccano/tree/visible_multiuser_annotation

**Comment by zhangxieyang2** [comment]
> Hello @zhangxieyang2. For sequence annotations, I have modified the source code to be able to view the annotations from multiple users. Here is the branch https://github.com/hkaraoguz/doccano/tree/visible_multiuser_annotation

Thank you so much!
