### ISSUE TITLE
after annotating 4 or 5 documents, no further annotations are displayed

### ISSUE THREAD

**Issue by hokreb** [chakki-works/doccano#243]
### System information
- **OS version**: debian 9.7 stretch, with apache2 and doccano installed by docker and postgresql 
- **Python version**: python 3.6

### Describe the problem
First thank you very much for this really nice application. I have installed doccano from docker image, changed only the settings part with database, so that postgressql is used

When I added a text file 
[sample3.txt](https://github.com/chakki-works/doccano/files/3289579/sample3.txt)
as document for sequence labeling, I can only annotate four or five sentences, than there will be presented an empty text and no more annotation will be available. I tried to use plan text file, but also tried to use json file, the same behaviour. I tried with admin user and "normal" user, no difference.

Is the text file wrong?

best regards
   hokreb

**Comment by icoxfog417** [comment]
Thank you for reporting the issue. I can not reproduce your issue. Please check the following points.

* Uer latest (master) doccano.
* Your data is imported correctly.

![image](https://user-images.githubusercontent.com/544269/59544950-7edcca80-8f52-11e9-93c6-94b0a223f9e8.png)

**Comment by hokreb** [comment]
Thank you a lot for testing this problem!
I reinstalled the system, this time, I used the original docker container you provided on docker hub, without any changes, imported the data, and I also see like you in the screenshot the "About 18 results". When I start to annotate, everything works fine, but after the last dataset of the first view is finished, and i press the "Next" button, an empty dataset is displayed. There are no new datasets shown at the side (I add a screenshot). 

![image](https://user-images.githubusercontent.com/3911448/59783223-f8ace500-92bf-11e9-8177-1e29fd822fec.png)

This is running on a machine, which is reachable in the internet, and served by apache2 with https and letsencrypt. A proxy and reserve proxy settings are use from apache2. Is there any special configuration of the apache2 server needed? 

If it would help, I can set up a user account for you, so that you might see the problem.

Any other idea, what could lead to this problem ?

best regards
hokreb

**Comment by hokreb** [comment]
I have tried to dig deeper to find the cause of the problem. As I have written above, I use proxypass of the apache2 on the docker host. The reason, that after 5 entries no new entries are shown, seems to be the javascript function, which asked for the next five datasets:

![image](https://user-images.githubusercontent.com/3911448/59918587-6c1c3700-9425-11e9-95b1-81070d0b6968.png)

This functions calles the http://localhost:8000/, exactly the exposed port of the docker container. If I replace the localhost:8000 with the real servername, a response is created correctly. 

Does anybody knows, If I have to change some settings of the javascript framework used in this app?

best regards
   hokreb

**Comment by jansaputra** [comment]
I have the same problem when using it behind a reverse proxy (nginx). For me, it seems that the servername is correct. But I use SSL and a javascript function seems to try to pull new data from a URL starting with http:// instead of https://. That causes my browser (Firefox) to block with the error "Blocked loading mixed active content". So it seems that the URL is build inside javascript somewhere but without determining the protocol, which seems to be hardcoded to be http://. Is there something like a configuration parameter that we need to set?

**Comment by sebastianionita82** [comment]
Try set this on apache, nginx has something similar.
       ProxyPreserveHost On
       RequestHeader set X_FORWARDED_PROTO 'https'
       ProxyPass  http://127.0.0.1:8000/ timeout=600
       ProxyPassReverse  http://127.0.0.1:8000/

**Comment by jansaputra** [comment]
Thank you a lot, the following settings solved the problem for me:

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
            proxy_pass http://localhost:8000;
