### ISSUE TITLE
When the number of labels is more than 15, colors are difficult to distinguish

### ISSUE THREAD

**Issue by Juntai** [chakki-works/doccano#253]
The UI of doccano is very beautiful! 
I have a project of sequence labeling with many labels, about 20 labels. doccano use COLOR to distinguish labels, but it is difficult to distinguish labels when there are too many labels.
I know I can use shortcut to label them, but when I review the labeled sequences to correct them, it is very difficult to distinguish labels.
![image](https://user-images.githubusercontent.com/4479020/59905776-a8599280-9439-11e9-9f4c-06653f8570bd.png)

There may be one way to solve that:
Add label names around the sequences text, left or above it.

**Comment by clarus** [comment]
Just having the same problem! I was thinking about adding a tooltip under the annotations:
![image](https://user-images.githubusercontent.com/316665/59909267-906d1900-940f-11e9-8953-925a76cf11a9.png)

**Comment by Juntai** [comment]
Thank you , clarus. I think this style may be better: https://prodi.gy/demo?view_id=pos_manual

**Comment by clarus** [comment]
Ah OK, I did not want to make too much change to the code and the presentation.
