### ISSUE TITLE
Display Error

### ISSUE THREAD

**Issue by Juntai** [chakki-works/doccano#257]
The left red rectangle text is copied by the system, it is not in my original text.
![标签显示问题-d](https://user-images.githubusercontent.com/4479020/60072058-e06d1800-974e-11e9-9b0d-a8564fa4943d.png)
![标签显示问题-o](https://user-images.githubusercontent.com/4479020/60072060-e105ae80-974e-11e9-8589-7b3f7279771d.png)

**Comment by Alan-buaa** [comment]
[https://github.com/chakki-works/doccano/pull/260](url)
