### ISSUE TITLE
Display Bug When Adding a Label to a Sequence Labeling Project

### ISSUE THREAD

**Issue by johnmccain** [chakki-works/doccano#259]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10, using latest Doccano Docker image (as of 06/25/19)
- **Python version**: n/a, using Docker image

### Describe the problem
When creating a new label for a sequence labeling project, what appears to be a css class (`is-medium`) appears visibly in error.

![image](https://user-images.githubusercontent.com/17013636/60129676-2c25be80-975b-11e9-97b7-c1fcc167385a.png)

### Source code / logs

Here's the relevant markup as viewed from the client.

```
<div class="tags has-addons mb0">
  <span
    class="tag is-medium"
    style="color: rgb(255, 255, 255); background-color: rgb(32, 156, 238);"
    >Product</span
  ><span class="tag">is-medium<kbd>p</kbd></span>
</div>
```

**Comment by c-w** [comment]
Should be fixed in https://github.com/chakki-works/doccano/pull/272.
