### ISSUE TITLE
Is there any development plan of doccano?

### ISSUE THREAD

**Issue by bifeng** [chakki-works/doccano#26]
I found some useful links: 
[prodi.gy](https://prodi.gy/demo)
[Chinese-Annotator](https://github.com/deepwel/Chinese-Annotator)

The prodigy using active learning structure, and automatic push some hard samples to be labeled (This is very difficult).
The Chinese-Annotator using the same structure of prodigy, but it's no longer development.

I am very interested in the active learning parts, is there any possible to write some todo list or development plan？

**Comment by BrambleXu** [comment]
Thanks for your concern. There is no plan to support the active learning feature, but there is another feature named auto labeling. Maybe this is close to what you want. #18

**Comment by bifeng** [comment]
Thanks.

**Comment by jamesmf** [comment]
the auto_labeling feature + #20  would enable you to re-order your examples according to whatever active learning objective you wanted.

**Comment by icoxfog417** [comment]
About the reason that we don't include active learning, please refer [#6](https://github.com/chakki-works/doccano/issues/6#issuecomment-431533404).
