### ISSUE TITLE
Heroku postdeploy execution timed out

### ISSUE THREAD

**Issue by john-dugan** [chakki-works/doccano#262]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Heroku via https://dashboard.heroku.com/new?template=https://github.com/chakki-works/doccano/
- **Python version**: 
3.6

### Describe the problem
Deploying a new Heroku app with https://dashboard.heroku.com/new?template=https://github.com/chakki-works/doccano/ is failing on the 'Run scripts & scale dynos' step.  Everything before that with the environment setup and building appear to be succeeding.  It could be related to https://github.com/chakki-works/doccano/issues/236 and https://github.com/chakki-works/doccano/pull/237 ?

### Source code / logs

Here's how far the 'Run scripts & scale dynos' step gets before timing out:

[36;1mOperations to perform:[0m
[1m  Apply all migrations: [0madmin, api, auth, contenttypes, sessions, social_django
[36;1mRunning migrations:[0m
  Applying contenttypes.0001_initial...[32;1m OK[0m
  Applying auth.0001_initial...[32;1m OK[0m
  Applying admin.0001_initial...[32;1m OK[0m
  Applying admin.0002_logentry_remove_auto_add...[32;1m OK[0m
  Applying admin.0003_logentry_add_action_flag_choices...[32;1m OK[0m
  Applying contenttypes.0002_remove_content_type_name...[32;1m OK[0m
  Applying api.0001_initial...[32;1m OK[0m
  Applying auth.0002_alter_permission_name_max_length...[32;1m OK[0m
  Applying auth.0003_alter_user_email_max_length...[32;1m OK[0m
  Applying auth.0004_alter_user_username_opts...[32;1m OK[0m
  Applying auth.0005_alter_user_last_login_null...[32;1m OK[0m
  Applying auth.0006_require_contenttypes_0002...[32;1m OK[0m
  Applying auth.0007_alter_validators_add_error_messages...[32;1m OK[0m
  Applying auth.0008_alter_user_username_max_length...[32;1m OK[0m
  Applying auth.0009_alter_user_last_name_max_length...[32;1m OK[0m
  Applying sessions.0001_initial...[32;1m OK[0m
  Applying social_django.0001_initial...[32;1m OK[0m
  Applying social_django.0002_add_related_name...[32;1m OK[0m
  Applying social_django.0003_alter_email_max_length...[32;1m OK[0m
  Applying social_django.0004_auto_20160423_0400...[32;1m OK[0m
  Applying social_django.0005_auto_20160727_2333...[32;1m OK[0m
  Applying social_django.0006_partial...[32;1m OK[0m
  Applying social_django.0007_code_timestamp...[32;1m OK[0m
  Applying social_django.0008_partial_timestamp...[32;1m OK[0m

**Comment by icoxfog417** [comment]
We already confirm this phenomenon. It is caused by `collectstatic` that took a long time after the project structure changed.

**Comment by nobillygreen** [comment]
Is there a solution to this? I'm also running into the same bug when deploying to Heroku.

**Comment by john-dugan** [comment]
Does anyone happen to know if https://doccano.herokuapp.com is running the latest code from the master branch, and if so, what steps we can take to deploy updates on Heroku too?

**Comment by john-dugan** [comment]
If I am able to successfully build+deploy on Heroku with the updated code, it looks like I'm running into the 30sec timeout limit for the workers.  I tried using one of the 2x dynos with 1GB RAM as well, but that didn't appear to help.

```
19:23:58.034769+00:00 heroku[web.1]: Starting process with command `gunicorn --pythonpath app app.wsgi`
19:24:01.022847+00:00 heroku[web.1]: State changed from starting to up
19:24:00.554213+00:00 app[web.1]: [2019-07-10 19:24:00 +0000] [4] [INFO] Starting gunicorn 19.9.0
19:24:00.555087+00:00 app[web.1]: [2019-07-10 19:24:00 +0000] [4] [INFO] Listening at: http://0.0.0.0:54038 (4)
19:24:00.555239+00:00 app[web.1]: [2019-07-10 19:24:00 +0000] [4] [INFO] Using worker: sync
19:24:00.559621+00:00 app[web.1]: [2019-07-10 19:24:00 +0000] [10] [INFO] Booting worker with pid: 10
19:24:00.571011+00:00 app[web.1]: [2019-07-10 19:24:00 +0000] [11] [INFO] Booting worker with pid: 11
19:24:21.030113+00:00 heroku[web.1]: Process running mem=533M(104.1%)
19:24:21.030113+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
19:24:31.079567+00:00 app[web.1]: [2019-07-10 19:24:30 +0000] [4] [CRITICAL] WORKER TIMEOUT (pid:10)
19:24:31.084623+00:00 app[web.1]: [2019-07-10 19:24:31 +0000] [4] [CRITICAL] WORKER TIMEOUT (pid:11)
19:24:31.089634+00:00 app[web.1]: [2019-07-10 19:24:31 +0000] [10] [INFO] Worker exiting (pid: 10)
19:24:31.092828+00:00 app[web.1]: [2019-07-10 19:24:31 +0000] [11] [INFO] Worker exiting (pid: 11)
```

**Comment by Hironsan** [comment]
[https://doccano.herokuapp.com](https://doccano.herokuapp.com) is not running the latest code.

**Comment by kbst9** [comment]
Getting the same issue. Is there a specific commit to reset to that's recommended for Heroku?

**Comment by john-dugan** [comment]
@kbst9 I'm running https://github.com/chakki-works/doccano/commit/801baf37ec07977b07ecea63b7176e58f58f8b56 but if there's anything newer that works that would be helpful too.

**Comment by kbst9** [comment]
Thanks @john-dugan! Trying a few others after that then, will keep you updated.
