### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by raady07** [chakki-works/doccano#263]
I have cloned the repository and trying to install the requirements.txt in doccano folder. 

I get the following error

Collecting psycopg2 (from django-heroku==0.3.1->-r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/5c/1c/6997288da181277a0c29bc39a5f9143ff20b8c99f2a7d059cfb55163e165/psycopg2-2.8.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
    
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-wbhbzuco/psycopg2/

I have tried installing psycopg2 manually and tried some commands

sudo apt-get install python-psycopg2 psycopg2-binary
sudo pip install -U setuptools

but still it has the same error, how to resolve it ?

**Comment by c-w** [comment]
[django-heroku depends on psycopg2](https://github.com/heroku/django-heroku/blob/8396b5544c36274942ee6d16ab46d4cddcdd3b4b/setup.py#L23) so that library's dependencies must be present before installing the requirements. Try `sudo apt-get install libpq-dev` and the installation should work.

**Comment by raady07** [comment]
Thank you it worked !
