### ISSUE TITLE
Automatically show next data after labelling

### ISSUE THREAD

**Issue by raibosome** [chakki-works/doccano#267]
### System information
- macOS 10.14
- Python 3.7

### Describe the problem
May I propose a feature where once a user hits the Enter after annotating (machine translation), it automatically goes to the next data to label? I think this might increase speed ups in labelling data

**Comment by icoxfog417** [comment]
Thank you for your proposal. 
How do you think about detecting "end of the annotation"? If would be difficult to separate whether annotator is thinking/ posing or ends their work.

**Comment by raibosome** [comment]
Personally I would set the default as go to the next example, and have an
option to disable this.

**Comment by Accagain2014** [comment]
the feature may be very useful and will speed up the progress of labeling, especially in document classification task.

**Comment by icoxfog417** [comment]
[It is considered in new UI](https://github.com/chakki-works/doccano/pull/341).

**Comment by jpmorris** [comment]
This is easy for classification. As soon as you classify, the 'annotation' is done
