### ISSUE TITLE
端口被占用

### ISSUE THREAD

**Issue by jtyoui** [chakki-works/doccano#279]
[root@machinelearn app]# python3 manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
July 09, 2019 - 03:24:22
Django version 2.2.3, using settings 'app.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Error: That port is already in use.

**Comment by Lijiachen1018** [comment]
specify your port like this:
python3 manage.py runserver 0.0.0.0:8999

or replace '8999' by the number you like.
