### ISSUE TITLE
can't annotate two neighbor entity in a sentence?

### ISSUE THREAD

**Issue by phiedulxp** [chakki-works/doccano#28]
```
can:
xx ORG xx ORG xx
can't:
xx ORG ORG xx
```

**Comment by BrambleXu** [comment]
I test your case with my text locally, and it works well. Could you give us more detail about your data?

**Comment by phiedulxp** [comment]
> I test your case with my text locally, and it works well. Could you give us more detail about your data?

it only happen in language which has no blank space between words.
这个工具不是未中文设计的！
如果分词后再标注，错分时需要跨空格划词。

**Comment by BrambleXu** [comment]
Thanks for the demo.  I reimplemented it.  I will work on this problem.

**Comment by Hironsan** [comment]
Solved by https://github.com/chakki-works/doccano/pull/30.

Thanks @BrambleXu !
