### ISSUE TITLE
Feature request: Simultaneous NER and Classification (intent labeling)

### ISSUE THREAD

**Issue by Zylatis** [chakki-works/doccano#282]
Hello,

I'm really thrilled to have found this package as it's exactly what I am hunting for - however I would like the ability to simultaneously label entities within the text while giving an overall sentiment and/or intent classification for the text as a whole. As I understand it (from briefly playing around with it) these are considered separate tasks and so I would need to run over each bit of text twice in order to get all the info. Is this correct or am I missing some functionality already available?

Thanks!
Z

**Comment by Hironsan** [comment]
> As I understand it (from briefly playing around with it) these are considered separate tasks and so I would need to run over each bit of text twice in order to get all the info. Is this correct or am I missing some functionality already available?

Correct. As of now, doccano doesn't support annotation for NER and text classification at the same time.

**Comment by c-w** [comment]
This would be a nice feature to implement and would enable doccano to integrate with bot frameworks like [LUIS](https://www.luis.ai/) which often work on sequence annotation plus utterance classification at the same time.

**Comment by Zylatis** [comment]
Yep, bot conversation annotation is precisely the task I am working on!

**Comment by SachinKalsi** [comment]
@Zylatis Any idea when it will be released?

**Comment by SachinKalsi** [comment]
Any idea when this feature will be released?

**Comment by muhnashX** [comment]
any updates on this *awesome* feature?

**Comment by bonehead** [comment]
> any updates on this _awesome_ feature?

Any replies would be greatly appreciated :)

**Comment by SimZhou** [comment]
Any Updates on this feature?

**Comment by madkote** [comment]
@icoxfog417 Hi, could you please clarify if that feature request will be included into the roadmap? or if the feature already implemented. Thanks!

**Comment by tom9358** [comment]
I would also be very interested in this feature!
