### ISSUE TITLE
Documents for sequence labeling are not in correct order

### ISSUE THREAD

**Issue by comma3** [chakki-works/doccano#283]
Thank you for this great tool!

I seem to have run across a bug with the sequence labeling. It does not show documents in the correct order (matching the order in the database). I have Randomize Document Order set to False. I have even seen it show duplicate documents while omitting others.

I used the deploy to azure button in the readme and made no other modifications.

Has anyone seen this before?

**Comment by icoxfog417** [comment]
Please raise a new issue if you still face this phenomenon.
