### ISSUE TITLE
Feature Request: Avoid the overlap of annotation for each user

### ISSUE THREAD

**Issue by miskolc** [chakki-works/doccano#288]
When I create a text classification project and add multiple annotators I see they will be given the same annotations by default. I would want them to annotate different texts and if one user has annotated one text, I want the other users to be given a different text when they click on next.
I see the only way to ensure users are not annotating the same texts is to make sure they always click on Active option of the dropdown in the top-left of the screen. That is not very good from a UX perspective.
I know prodigy gives different batches to users by default.
Is there any possibility to achieve this in a easer manner at the moment with doccano?

If not, can this feature be added in the future?

**Comment by icoxfog417** [comment]
For now, you have to separate the project if you want to split the texts for each annotator.
We consider implementing this feature according to its requires in community.

**Comment by c-w** [comment]
One way to address the use case of minimizing annotation overlap today is to use per-user document order randomization. See https://github.com/chakki-works/doccano/issues/201 for more details.

**Comment by icoxfog417** [comment]
https://github.com/chakki-works/doccano/pull/230
