### ISSUE TITLE
Users who did not create a project cannot see the project

### ISSUE THREAD

**Issue by nobillygreen** [chakki-works/doccano#289]
Users that I add to a project cannot see the project in their projects page. I have an admin that has created the project, and on the page at /admin/server/textclassificationproject/3/change/ the users are listed under 'Users', but they still cannot see the project.

**Comment by nobillygreen** [comment]
I misunderstood how 'adding a user to a project' worked in the django admin dashboard. Did not realize you had to highlight them and then click save for them to show up.

**Comment by Zylatis** [comment]
Agreed - this is not at all clear and only learned how to do this after reading the above - can this instruction be put explicitly somewhere?
