### ISSUE TITLE
Stats page bug - annotation progress is incorrect

### ISSUE THREAD

**Issue by miskolc** [chakki-works/doccano#292]
It used to be that the percentage completed was aggregated across all people with whom a dataset was shared.
I've noticed now it's only aggregated on the admin's annotation stats which is not useful as in many cases the Admin doesn't annotate, the annotators do that and it's useful to know what did the annotated

**Comment by c-w** [comment]
Likely related to https://github.com/chakki-works/doccano/pull/230.

**Comment by miskolc** [comment]
@c-w I see. Thanks for spotting that. It does makes sense for users to see their progress but I also think it makes sense for the admins to see the totals especially if you have multiple annotators per project being fed with random streams of sentences

**Comment by icoxfog417** [comment]
#230 is merged. Please raise a new issue if you want to switch progress depends on the role.
