### ISSUE TITLE
AWS CloudFormation URL?

### ISSUE THREAD

**Issue by krishkumar** [chakki-works/doccano#300]
I used the Launch Stack feature to automate setting up doccano on AWS. 

Checked out CloudFormation logs and everything seems to have went well. Region: US East (N. Virginia)

On trying to access the app using the Public DNS of the EC2 instance or the public IP, it is not connecting at all. 

Is doccano hosted at a specific port that I should use with the public dns url? 

Any help would be appreciated.

**Comment by icoxfog417** [comment]
[doccano launches on the port 80 (ordinaly HTTP)](https://github.com/chakki-works/doccano/blob/master/awsdeploy.yml#L8). If you want to use HTTPS, please refer the following document.

https://github.com/chakki-works/doccano/wiki/HTTPS-setting-for-doccano-in-AWS

Please let me tell what "not connecting" means? You can not reach the host (ping does not work), or return some HTTP error?

**Comment by krishkumar** [comment]
Yes cloud formation setup this instance and I am trying to access it with the public url of the ec2 instance, as so. 

`http://ec2-54-209-67-74.compute-1.amazonaws.com/`

**Comment by icoxfog417** [comment]
Thank you for reporting. Can you reach the host (`ping ec2-54-209-67-74.compute-1.amazonaws.com` work)? If you can't reach the host, your server does not launch correctly (it does not HTTP port issue).

**Comment by krishkumar** [comment]
Turns out ping didn't work either. Thank you for debugging this one. I will try this again.

**Comment by katreparitosh** [comment]
@krishkumar Were you able to resolve the issue? If yes, it would be great if you could share it.
