### ISSUE TITLE
when I try to setup the program on the server, came from error of egg_info?after searching ,when doing approach of  Command "python -m pip install django-heroku==0.3.1,then I get error, it shows ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-i nstall-tjd825fx/psycopg2/,  is there anyone knows how it happens ?and how to solve it?

### ISSUE THREAD

**Issue by xiexiang95** [chakki-works/doccano#307]
If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**: 

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by c-w** [comment]
This looks like the postgres system dependencies are missing. Did you set up the Python environment as described in [README.md](https://github.com/chakki-works/doccano/blob/7e2ba5dd36de6fb372d8702e74d8de82d70a1e4c/README.md) _Option2: Setup Python environment_ via `sudo apt-get install libpq-dev`?

**Comment by xiexiang95** [comment]
Thanks for you reply, after trying another step of setup it, then it succeed.thanks




------------------ 原始邮件 ------------------
发件人: "Clemens Wolff"<notifications@github.com>;
发送时间: 2019年7月27日(星期六) 凌晨5:28
收件人: "chakki-works/doccano"<doccano@noreply.github.com>;
抄送: "谢项"<1242530248@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chakki-works/doccano] when I try to setup the program on theserver, came from error of egg_info?after searching ,when doing approach of Command "python -m pip install django-heroku==0.3.1,then I get error, it showsERROR: Command "python setup.py egg_info" failed with error code 1 in/tmp/pip-i nstall-tjd825fx/psycopg2/,  is there anyone knows how it happens?and how to solve it? (#307)




This looks like the postgres system dependencies are missing. Did you set up the Python environment as described in README.md Option2: Setup Python environment via sudo apt-get install libpq-dev?
