### ISSUE TITLE
Skip forward

### ISSUE THREAD

**Issue by Zylatis** [chakki-works/doccano#310]
Hi I am trying to find a way to skip back to the previous spot when i log back out and in, is this possible? I have tried just skipping forward by pressing the right arrow but it seems quite slow (it rubber bands and jumps back all the time) and editing the url path doesn't seem to make a difference.

Thanks
Z

**Comment by c-w** [comment]
@armanrahman22 and @fnocera are working on a UI to skip forward/backwards an entire page of documents which will speed up the navigation process, as well as on some improvements to the "UI jumping while scrolling through documents" issue. The pull request should be ready soon.

**Comment by Zylatis** [comment]
Great! This will be extremely useful. Will this include the ability to have users resume their previous spot in the data stack when they log back in to save navigating through again?

**Comment by c-w** [comment]
https://github.com/chakki-works/doccano/pull/328 introduced two ways to improve the situation described in this issue: (1) an option to increase the pagination size via an environment variable and (2) a button to skip a page forward instead of only one document.

**Comment by Zylatis** [comment]
Awesome, thanks - any chance of also getting bookmarks? Basically send a given user to the place they last left off (assuming the underlying data is unchanged/not reordered or anything)

**Comment by icoxfog417** [comment]
Please raise a new issue if you want the new feature (bookmark).
