### ISSUE TITLE
Cannot share annotated data among users

### ISSUE THREAD

**Issue by jinhojang6** [chakki-works/doccano#313]
When we add a user into a project, what the user did is not shown to the admin's side(and others).

There is no way to check what the added users do except for the statistics page.

**Comment by icoxfog417** [comment]
Do you mean the admin can not access the annotation data made by the added (new) user?

**Comment by jinhojang6** [comment]
yes, I found that all the user's work is aggregated and downloaded as a json file.

I think it would be great to sync what other users did on the admin's annotation panel.

**Comment by c-w** [comment]
@jinhojang6 I've implemented an option to enable all users on a project to share annotation progress in https://github.com/chakki-works/doccano/pull/318. Could you take a look and let me know if this suits your requirements?

**Comment by jinhojang6** [comment]
Hmm, It didn't work on my end. I cannot find the list of projects

**Comment by jinhojang6** [comment]
@c-w It works fantastically well. Thanks you for the guide

**Comment by akailcy** [comment]
great works @c-w! I add collaborative_annotation function according to your commit, I'm confused about that admin can see user's annotation, but he can't modify the annotation, in annotation task, it's better for someone to check the annotation results in the panel, and modify it, could you please add the request?

**Comment by c-w** [comment]
@akailcy My team is currently working on improvements to roles in doccano, including introducing a label approver role similar to what you're mentioning. See https://github.com/chakki-works/doccano/issues/152#issuecomment-520959755 for more context. We're also working on a specific view to approve labels more effectively. Stay tuned for these changes.
