### ISSUE TITLE
No response after attempting to upload file

### ISSUE THREAD

**Issue by pranay725** [chakki-works/doccano#323]
I was trying to upload the following document to a project. The uploader recognizes the file name but fails to upload the data to the project. The portal does not issue any error messages either. No issues on the heroku log as well.Are there any other constraints that I should be aware about?  

`{"text": " Background: Ebola is a virus that has infected and killed people mostly in West Africa. There is no treatment or prevention for it, but several drugs are being studied. Researchers want to test the drug MAb114 in healthy people not exposed to Ebola to see whether it can be used for Ebola treatment in people who are infected in the future. This trial will not expose volunteers to the Ebola virus. Objectives: To see if MAb114 is safe and how a person's body responds to it. Eligibility: Healthy adults ages 18-60 who weigh 220.5 pounds or less Design: Participants will be screened under protocol NIH 11-I-0164 with:   -  Medical history   -  Physical exam   -  Blood or urine tests Participants will have a first 8- to10-hour visit. They will get MAb114 by IV infusion. For this, a thin tube will be placed in an arm vein. They may get an IV line in their other arm to collect blood. Blood will be taken many times before and after the infusion. Participants may have a urine test. Participants will get a thermometer to check their temperature for 3 days after they get MAb114. They will record their highest temperature and any symptoms. Participants will have about 14 more study visits over 6 months. At each visit, they will have blood taken and be checked for any health changes. They will talk about how they are feeling and if they have taken any medications. At the end of the 6 months, participants may be invited to take part in another study for follow-up sample collection.    ","labels": [[13, 18, "ORGANISM"], [59, 65, "ORGANISM"], [204, 210, "GENE_OR_GENE_PRODUCT"], [59, 65, "ORGANISM"], [13, 18, "ORGANISM"], [13, 18, "ORGANISM"], [59, 65, "ORGANISM"], [387, 398, "ORGANISM"], [204, 210, "GENE_OR_GENE_PRODUCT"], [600, 613, "CELL"], [665, 670, "ORGANISM_SUBSTANCE"], [674, 679, "ORGANISM_SUBSTANCE"], [204, 210, "GENE_OR_GENE_PRODUCT"], [791, 795, "TISSUE"], [817, 825, "MULTI-TISSUE_STRUCTURE"], [817, 820, "ORGANISM_SUBDIVISION"], [881, 886, "ORGANISM_SUBSTANCE"], [665, 670, "ORGANISM_SUBSTANCE"], [204, 210, "GENE_OR_GENE_PRODUCT"], [881, 886, "ORGANISM_SUBSTANCE"]]}`

**Comment by pranay725** [comment]
on further analysis I found this error on the browsers console 

`VM209:1 POST https://pubtator.herokuapp.com/v1/projects/12/docs/upload 500 (Internal Server Error)
(anonymous) @ VM209:1
(anonymous) @ upload_sequence_labeling.a97f96ec9339.js:1
e.exports @ upload_sequence_labeling.a97f96ec9339.js:1
e.exports @ upload_sequence_labeling.a97f96ec9339.js:1
Promise.then (async)
s.request @ upload_sequence_labeling.a97f96ec9339.js:1
s.<computed> @ upload_sequence_labeling.a97f96ec9339.js:1
(anonymous) @ upload_sequence_labeling.a97f96ec9339.js:1
upload @ upload_sequence_labeling.a97f96ec9339.js:8
change @ upload_sequence_labeling.a97f96ec9339.js:1
t @ upload_sequence_labeling.a97f96ec9339.js:14
Mr.t._withTask.o._withTask @ upload_sequence_labeling.a97f96ec9339.js:14
upload_sequence_labeling.a97f96ec9339.js:8 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'detail' in <h1>Server Error (500)</h1>
    at upload_sequence_labeling.a97f96ec9339.js:8
    at Array.forEach (<anonymous>)
    at a.handleError (upload_sequence_labeling.a97f96ec9339.js:8)
    at upload_sequence_labeling.a97f96ec9339.js:8`

**Comment by zyjcs** [comment]
> Hi @pranay725, I also ran into similar issues on upload. A few things that I found helpful:
> 
> * Make sure all of the labels are defined before trying to import
> * Try removing the duplicate labels such as  `[13, 18, "ORGANISM"], [13, 18, "ORGANISM"]`
> * I'm not sure if overlapping labels are supported yet, so `[817, 825, "MULTI-TISSUE_STRUCTURE"], [817, 820, "ORGANISM_SUBDIVISION"]` might be causing issues too.

![8785855746546](https://user-images.githubusercontent.com/18757695/64163742-65be2880-ce74-11e9-9d2d-d5679b467c9d.png)
no response? I chose a .csv file ，and did not upload successful ,I  use docker .

**Comment by zyjcs** [comment]
![222222222222222](https://user-images.githubusercontent.com/18757695/64164290-85098580-ce75-11e9-8c91-4a13c46fef17.png)
and  my data1.csv  like this  ,i don't know how  to upload the data ,i want do a NER  annotation。

**Comment by icoxfog417** [comment]
@pranay725 You have many overwrapping in your JSON file. I confirmed the file can be upload by removing these.
 @ zyjcs Please confirm your file encoding and other formatting issue [FAQ: I can't upload my data.](https://github.com/chakki-works/doccano/wiki/Frequently-Asked-Questions#i-cant-upload-my-data).

**Comment by waterflyer** [comment]
Hi, @icoxfog417 I'm facing the same issue here. 

I did create the labels before importing data, also I can ensure that there is no overlapping or duplicated labels in my data. I can give you one example:
{"text": "Hi xxx! Thank you for sharing your experience with our XXXX. We're sorry to hear that you don't love this product! Feedback from our consumers is very important to us and helps us improve all of our products. We hope you will continue to explore our products with complete confidence and satisfaction.", "labels": [[66, 106, "Product"]]}

When I check the Chrome console, I can see the following issue
![image](https://user-images.githubusercontent.com/23243356/86961442-d8e49b00-c126-11ea-8137-668e0f7ac53d.png)

Therefore, could you help me figure out where is the problem? I wanted to display the annotation in the predicted NER model by uploading the text and labels into Doccano, is that possible?

Thank you so much!

**Comment by Vital95** [comment]
Hello, I have had save issue, it was some mess with lists in my case.
I was trying to upload text in list. that was the case, hope it could help you.
