### ISSUE TITLE
cannot get cdnjs for css files

### ISSUE THREAD

**Issue by frankchen7788** [chakki-works/doccano#324]
after docker run, the browser UI doesn't work normally.
as shown is web console 
cannot get https://cndjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css
.....

what should to do?

**Comment by c-w** [comment]
Is it possible that your local checkout has a typo? I notice c**nd**js in the URL but it should be c**dn**js ([the spelling is currently correct in the master branch](https://github.com/chakki-works/doccano/blob/47e54e4c2a27379d51d4bd9860f7fbef8b0c2693/app/server/templates/base.html#L15)).
