### ISSUE TITLE
docker-compose pull error

### ISSUE THREAD

**Issue by FzuGsr** [chakki-works/doccano#329]
**System information**
windows7 

**Source code / logs**
```
Option3: Pull the development Docker-Compose images
docker-compose pull,
```
When running the command docker-compose pull, the following error message appears:
$ docker-compose pull
Pulling webpack (node:8)...
ERROR: SSL error: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)

how do i solve this? thank you 

My docker-compose version is
$ docker-compose version
docker-compose version 1.18.0, build 8dd22a96
docker-py version: 2.6.1
CPython version: 2.7.14
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

**Comment by c-w** [comment]
This looks like an issue with Docker on Windows 7 to me, not with doccano. Try setting the environment variable `COMPOSE_TLS_VERSION=TLSv1_2` and see if that fixes the problem (as documented [here](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_app_dev/deploy_multiple_docker_compose.html) and [here](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_app_dev/container_limitations.html)).
