### ISSUE TITLE
how can i use collaborative annotation

### ISSUE THREAD

**Issue by akailcy** [chakki-works/doccano#331]
according to the install guide, I reinstall the doccano, and start it with manage.py, but I don't see any difference between new and old version, when I create a new project, there is no "share annotations across all users" option, can anyone provide some specific guideline to this new feature?

**Comment by c-w** [comment]
The pull request that implements collaborative annotation (https://github.com/chakki-works/doccano/pull/318) still has to be merged by @Hironsan.

If you want to use the feature before the pull request gets merged, you'll have to check out the feature's branch using something along these lines:

```sh
git remote add catalystcode https://github.com/CatalystCode/doccano.git
git fetch catalystcode
git checkout enhancement/collaborative-annotation
```

**Comment by c-w** [comment]
@akailcy The feature has now been merged so you should be able to start using collaborative annotation using the latest doccano master.
