### ISSUE TITLE
请问对于合作标注，可以进行多人合作，分配标注任务。这个能讲详细点吗

### ISSUE THREAD

**Issue by WenNicholas** [chakki-works/doccano#336]
If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**: 

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by Hironsan** [comment]
Sorry, we cannot understand chinese. Please in English.

**Comment by WenNicholas** [comment]
First of all, thank you for your reply, your product is really great! I would like to consult: I would like to cooperate with the multi-person cooperation and assign the labeling task. Can you tell me more about this? Is everyone going to register an account, or just one person to register an account, and multi-person collaboration mark under the same account?
------------------ 原始邮件 ------------------
发件人: "Hiroki Nakayama"<notifications@github.com>;
发送时间: 2019年8月19日(星期一) 下午2:59
收件人: "chakki-works/doccano"<doccano@noreply.github.com>;
抄送: "奋斗的小蜗牛"<1344294218@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chakki-works/doccano] 请问对于合作标注，可以进行多人合作，分配标注任务。这个能讲详细点吗 (#336)




Sorry, we cannot understand chinese. Please in English.
