### ISSUE TITLE
An OSError...

### ISSUE THREAD

**Issue by ScottishFold007** [chakki-works/doccano#338]
![image](https://user-images.githubusercontent.com/36957508/63248537-197ec000-c29a-11e9-9ebc-3e8741f4ff0f.png)

**Comment by DaydreamerZhang** [comment]
I would like to ask the same question.

**Comment by DaydreamerZhang** [comment]
Have you installed nodejs and npm on your Windows? I also met the problem and it is fixed after I install nodejs on http://nodejs.org/.

**Comment by icoxfog417** [comment]
Please refer the following FAQ. It would be helpful for you.

https://github.com/chakki-works/doccano/wiki/Frequently-Asked-Questions#i-cant-install-doccano
