### ISSUE TITLE
Deployment to AWS fails

### ISSUE THREAD

**Issue by MalinowskiRoman** [chakki-works/doccano#340]
Hello, 
I followed [this tutorial](https://github.com/chakki-works/doccano/wiki/HTTPS-setting-for-doccano-in-AWSl) for deploying Doccano to an AWS server. I had no problem in any of the steps, except in the end I get a 502 Bad Gateway Error when I try to access the website.

A possible reason would be that I operate from Singapore while the availability zones selected in the ELB step were all in East US but I don't really know what they represent: are they the zones from where you can access the website, or is it only relevant for how it works internally?

Thanks by advance, I don't really know which details I should provide since every step worked exactly as in the tutorial but feel free to request more.

### System information
- **OS Platform and Distribution**: Windows 10
- **Python version**: Python 3.7

**Comment by BrambleXu** [comment]
The availability zones are only relevant internally. 
Does the http version work normally?

**Comment by MalinowskiRoman** [comment]
When I try to replace HTTPS by HTTP I have the same issue. 
Did it need prior settings before this tutorial ? I just followed the steps of the tutorial but I had no domain or server whatsoever before trying to put doccano on a server. Maybe the issue comes from there ?

**Comment by BrambleXu** [comment]
Yes. You should first build an http version doccano server. You can do this just by one-click and the one-click button is in the README. After build the server, you can convert it to https. The AWS setting is pretty troublesome, I recommend you choose Heroku one-click button, which will save your time.

**Comment by MalinowskiRoman** [comment]
All right, sorry for the trouble then. I did launch it with Heroku, it works perfectly. Thank you so much for your help !

**Comment by davidolmo** [comment]
Yes, it is not working on AWS. I followed the tutorial and couldn't make it work
