### ISSUE TITLE
Change the colour of metadata

### ISSUE THREAD

**Issue by gabrer** [chakki-works/doccano#343]
### Describe the problem
How to change the colour of metadata to a less bright and easy-to-read one?

**Example:**

> ![image](https://user-images.githubusercontent.com/6605510/63343946-2a393f80-c347-11e9-971b-bfc39a4df5db.png)

### Source code
I have tried to change the "annotation.css" by adding, but it gets override: 
```
.vjs-tree .vjs-value__string  {
   color: black;
}
```

### System information
- Linux Ubuntu 18.04
- Google Chrome 76
- Python 3.6

**Comment by icoxfog417** [comment]
[It is considering at new UI](https://github.com/chakki-works/doccano/pull/341)
