### ISSUE TITLE
Cannot create new labels

### ISSUE THREAD

**Issue by vanxoo** [chakki-works/doccano#345]
Hi all, 

I have a recurring issue when doing sequence labeling with Doccano. When creating a new project and adding labels to it, sometimes it tells me I cannot create a new label with the same name or same shortcut key, even though none of the other labels share it. It even happened with an empty project, with no other projects.

![image](https://user-images.githubusercontent.com/49099001/63408162-fb8f9780-c420-11e9-8b2d-a82eb34ef820.png)

It works again after deleting all the projects and starting over, but not every time.

The app is deployed on Heroku.

### System Information
OS: Windows 10
Doccano deployed on Heroku (master branch)

**Comment by Hironsan** [comment]
I fixed the label creation process in https://github.com/chakki-works/doccano/pull/347. Please check it.

**Comment by vanxoo** [comment]
It is still the case: 
![Capture](https://user-images.githubusercontent.com/49099001/63504379-040cce80-c504-11e9-8d2c-05100e52b116.PNG)
Here I could not create any label (but it was possible from another account)
