### ISSUE TITLE
Offset in the labelling

### ISSUE THREAD

**Issue by vanxoo** [chakki-works/doccano#346]
Hello, 

sometimes when working on a sequence labeling project, when I select a chunk of text and press a shortcut/button for labeling it, Doccano tries to label it a few characters late (for example 10 or 20 chars). It is very annoying and completely prevents one to correctly label a document.

It happens often, like once every 10 documents or more.

Thanks for your answers!

### System information
- **OS Platform and Distribution**: Windows 10
- **Python version**: 3.7 - Hosted on Heroku

**Comment by Hironsan** [comment]
Hello @vanxoo. Thank you for reporting.
Please show me your document and screenshot as an example.

**Comment by icoxfog417** [comment]
Please raise a new issue if you still face this phenomenon.
