### ISSUE TITLE
Site just hangs with Debug = False and ALLOWED_HOSTS = ['*'] in production server

### ISSUE THREAD

**Issue by h-2-0** [chakki-works/doccano#349]
If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 9.9
- **Python version**: 3.6.4

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug or a feature request.

I am using a private production server (not Heroku) with Gunicorn and Nginx as a proxy server. I am not sure if this is related but I was getting the 502 server error as soon as I changed to `Debug = False` and `ALLOWED_HOSTS = ['111.222.333.444']` in prod_settings.py.

I put logging in prod_settings.py to find out more about the issue and foiund this error:  `ValueError: Missing staticfiles manifest entry for 'admin/css/base.css'`. So I did a `python app/manage.py collectstatic --noinput -i node_modules`  and 502 server errors went away.

But now whenever I try to open a valid page it will just hang out and eventually Nginx will throw a 504 error (gunicorn workers will time out as well). 

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

From the Gunicorn logs this is the only thing I get (NOTE: I do not use Heroku): 
```
django_heroku.core INFO     $DATABASE_URL not found, falling back to previous settings!
django_heroku.core INFO     Applying Heroku Staticfiles configuration to Django settings.
django_heroku.core INFO     Applying Heroku ALLOWED_HOSTS configuration to Django settings.
django_heroku.core INFO     Applying Heroku logging configuration to Django settings.
django_heroku.core INFO     $DATABASE_URL not found, falling back to previous settings!
django_heroku.core INFO     Applying Heroku Staticfiles configuration to Django settings.
django_heroku.core INFO     Applying Heroku ALLOWED_HOSTS configuration to Django settings.
django_heroku.core INFO     Applying Heroku logging configuration to Django settings.
django_heroku.core INFO     $DATABASE_URL not found, falling back to previous settings!
django_heroku.core INFO     Applying Heroku Staticfiles configuration to Django settings.
django_heroku.core INFO     Applying Heroku ALLOWED_HOSTS configuration to Django settings.
django_heroku.core INFO     Applying Heroku logging configuration to Django settings.
[2019-08-23 21:15:55 +0000] [8813] [CRITICAL] WORKER TIMEOUT (pid:9014)
[2019-08-23 21:15:55 +0000] [8813] [CRITICAL] WORKER TIMEOUT (pid:9015)
[2019-08-23 21:15:55 +0000] [8813] [CRITICAL] WORKER TIMEOUT (pid:9017)
[2019-08-23 21:15:55 +0000] [9014] [INFO] Worker exiting (pid: 9014)
[2019-08-23 21:15:55 +0000] [9015] [INFO] Worker exiting (pid: 9015)
[2019-08-23 21:15:55 +0000] [9017] [INFO] Worker exiting (pid: 9017)
[2019-08-23 21:15:56 +0000] [9020] [INFO] Booting worker with pid: 9020
[2019-08-23 21:15:56 +0000] [8813] [DEBUG] 1 workers
[2019-08-23 21:15:56 +0000] [9021] [INFO] Booting worker with pid: 9021
[2019-08-23 21:15:56 +0000] [9023] [INFO] Booting worker with pid: 9023
[2019-08-23 21:15:56 +0000] [8813] [DEBUG] 3 workers
django_heroku.core INFO     $DATABASE_URL not found, falling back to previous settings!
django_heroku.core INFO     Applying Heroku Staticfiles configuration to Django settings.
django_heroku.core INFO     Applying Heroku ALLOWED_HOSTS configuration to Django settings.
django_heroku.core INFO     Applying Heroku logging configuration to Django settings.
django_heroku.core INFO     $DATABASE_URL not found, falling back to previous settings!
django_heroku.core INFO     Applying Heroku Staticfiles configuration to Django settings.
django_heroku.core INFO     Applying Heroku ALLOWED_HOSTS configuration to Django settings.
django_heroku.core INFO     Applying Heroku logging configuration to Django settings.
django_heroku.core INFO     $DATABASE_URL not found, falling back to previous settings!
django_heroku.core INFO     Applying Heroku Staticfiles configuration to Django settings.
django_heroku.core INFO     Applying Heroku ALLOWED_HOSTS configuration to Django settings.
django_heroku.core INFO     Applying Heroku logging configuration to Django settings.
```
Note that when using `Debug = True` in `prod_settings.py` I can access the website without any problem. 

I was getting the same problems in local development after setting `Debug = False` (i.e. getting 502 errors) but after collecting the staticfiles it started to work again.

Any pointers, ideas or suggestions? I'm stuck here. Thanks in advance!

**Comment by c-w** [comment]
To reduce potential for misconfiguration, I'd recommend to run the system via docker as described in [Usage](https://github.com/chakki-works/doccano#usage). The docker setup serves the app via gunicorn and static files are served by whitenoise which should alleviate the need for nginx. My team has been running the docker setup with DEBUG=false and a variety of other production settings without issues.

**Comment by h-2-0** [comment]
Thanks, @c-w! I already tried the Docker way but I failed. This is why I wanted to give it a go with my own server. In any case, I retried again but I'm afraid I'm still stuck. 

See, the instructions in Usage don't say anything about deploying doccano in production but in a development server.  

First attempt to run doccano from my production server using the Usage part as a guide:
```
# From Usage
git clone https://github.com/chakki-works/doccano.git
cd doccano
docker pull chakkiworks/doccano
docker run -d --rm --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=admin@example.com" \
  -e "ADMIN_PASSWORD=password" \
  -p 8000:8000 chakkiworks/doccano
```
```
# From FAQ
docker run -d --name doccano -p 8000:80 chakkiworks/doccano
docker exec doccano tools/create-admin.sh "admin" "admin@example.com" "password"
docker stop doccano
docker start doccano 
```

After following -separately- both instructions  I then go to `http://111.222.333.444:8000/login` and it just hangs out.  Both [Usage](https://github.com/chakki-works/doccano#usage) and [FAQ](https://github.com/chakki-works/doccano/wiki/Frequently-Asked-Questions) instructions don't say anything about  `Debug = False`, `ALLOWED_HOSTS = ['your-ip-address']` or `SECRET KEY` when deploying in production . 

So I enter the running container(`docker exec -it -u 0 container-ID bash`)  to edit the settings.py to make it more production-wise (i.e. `Debug = False`,   `ALLOWED_HOSTS = ['my-ip-address]`, `SECRET_KEY='my-secret-key' ). Then I exit the container, stop it it and then start it again. I go to `http://111.222.333.444:8000/login` and, again, it just hangs out.  

Am I missing something very obvious? What would be the correct steps to run Doccano in a production server? I have read bits from here and there (in the [issues](https://github.com/chakki-works/doccano/issues) section) but still can't figure it out. Please feel free to correct me. I'm not very familiar with docker.  Any help would be greatly appreciated. Thanks!

**Comment by c-w** [comment]
> So I enter the running container to edit the settings.py to make it more production-wise. Then I exit the container, stop it it and then start it again.

Any edits you make inside of the container will be discarded when the container is restarted. All configuration should be passed via environment variables, e.g. `docker run -e SECRET_KEY=... -e DEBUG=False`. You may have to make some code changes to wire-through additional settings such as `ALLOWED_HOSTS` and rebuild the image with `docker build -t chakkiworks/doccano .`.

**Comment by h-2-0** [comment]
Thanks, @c-w. I really appreciate you take the time to respond.  I actually rebuilt the image using an edited Dockerfile (envirnoment variables) and settings.py (`ALLOWED_HOST` bit). 

I still hangs out when I go to `http://111.222.333.444:8000/login/` from my web browswer..BUT I just noticed I can curl into the website from the remote server. So it seems everything is fine and now this network problem. I have no idea though. I'm researching about it as I write this.

**Comment by h-2-0** [comment]
I finally made it work! Besides everything I mentioned before I just had to pass my host's unused port 80 when doing `docker run`. For a reason I have yet to understand using my host's port 8000 (Django's development server default port) wasn't working.  
```
docker run -d --rm --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=my@email.com" \
  -e "ADMIN_PASSWORD=password" \
  -e "DEBUG=False" \
  -e "SECRET_KEY=mysecretkey" \
  -p 80:8000 doccano:myrebuilt
```
Thanks again, @c-w. I hope my issue helps a future reader.

**Comment by hamzalagrari** [comment]
@roperi how did you set up the allowed host when debuh - False

**Comment by roperi** [comment]
@hamzalagrari 

I don't remember since I don't have the server anymore. But in my notes i have this:
```
# Edit app.app.settings.py 
ALLOWED_HOSTS = ['doccano.mydomain.com']
```
