### ISSUE TITLE
Select/Deselect all labels keyboard shortcut - text classification (feature request)

### ISSUE THREAD

**Issue by h-2-0** [chakki-works/doccano#351]
Use case: Say I want to label a text with only one label but I'm being shown all possible labels (say 10), so instead of closing one by one by hand until I have the one I want, I think it would be great to close them all in one keystroke and chose the one I need. 

Do you think it could be useful?

**Comment by icoxfog417** [comment]
Please raise a new issue if you want this feature. I can't figure out the useful situation for most of doccano user.
