### ISSUE TITLE
Pagination on the Project page

### ISSUE THREAD

**Issue by jinhojang6** [chakki-works/doccano#353]
![image](https://user-images.githubusercontent.com/41753422/63682865-da211800-c833-11e9-919e-edd6afb17ffe.png)

On the project page above, if there are a lot of projects, a user or admin has to scroll down the page for a long time. (Let's say there are 50 projects WIP, the admin or user has to scroll down a plenty of projects to find the project to check)

For a better UX. a pagination like the screenshot below
![image](https://user-images.githubusercontent.com/41753422/63682969-21a7a400-c834-11e9-92fe-842d39fe4b03.png)

would be helpful to browse a lot of projects in an organized manner.

**Comment by icoxfog417** [comment]
[It is considering at new UI](https://github.com/chakki-works/doccano/pull/341)
