### ISSUE TITLE
Show only documents without annotations when sharing labels across users

### ISSUE THREAD

**Issue by gabrer** [chakki-works/doccano#355]
### Problem
When doing document classification with shared labels across users, the button which should show only the "Active" documents to be annotated, actually shows documents already annotated by other users.
That is a bit annoying as there is no direct way to jump to the still unlabelled documents.

### Additional info
![image](https://user-images.githubusercontent.com/6605510/63764249-5102f300-c8be-11e9-8ce2-d38d67e6f1c4.png)

### System information
- Ubuntu 18.04
- Python 3.6

**Comment by icoxfog417** [comment]
We understand the lack of features for annotation by multiple users. The most simple way is to separate the project for each annotator. And we support this task by #360 (surely this is temporal solution).

**Comment by gabrer** [comment]
Probably this can be marked as "Request feature", as now thanks to the #318 integration, it is just needed to change the "Active" button behaviour to have a first support for multiple users annotation.
