### ISSUE TITLE
Question about loading of labels.

### ISSUE THREAD

**Issue by SkotchZ** [chakki-works/doccano#356]
Thank you for your great project. I have some question about labeling system.
Cause there is no possibility to separate work between two or more people without overlapping, i created several amount of project and now i have to i`m trying to create labels for all these project. Is there any possibility to load same set of labels for all of these project? Also will be great if there is possibility to make them share the same colors in all projects. If there is a quick way to make it with django admin it will be also fine.

**Comment by icoxfog417** [comment]
We discuss this feature at #360.
