### ISSUE TITLE
Feature Request: Import / Export project setting.

### ISSUE THREAD

**Issue by icoxfog417** [chakki-works/doccano#360]
Implements feature to export/import project setting (ex: label/annotation guide etc).

Background: 
When annotating the data by multiple users, we frequently make same projects in the doccano (doccano does not have the feature to assign annotation data to each annotator yet, so split the data and make individual project is typical strategy). In this situation, make same label setting and copy & paste the annotation guide by hand is a painful task.

**Comment by atakanokan** [comment]
#356 is very necessary when updating docker images. Took me 2 hours to restore shortcuts for each label in the new container. Would be good to have a configuration file.

**Comment by Hironsan** [comment]
Resolves in https://github.com/chakki-works/doccano/pull/443.
