### ISSUE TITLE
many users at once

### ISSUE THREAD

**Issue by atif-zakaria** [chakki-works/doccano#361]
how we can work on the same project/ dataset in the same time many users(up to 5 PCS ) i've crated the users and all but how can i let them work from their machines should we install the app on all the machines !

**Comment by icoxfog417** [comment]
[Please refer the FAQ](https://github.com/chakki-works/doccano/wiki/Frequently-Asked-Questions#i-want-to-add-annotators).

**Comment by atif-zakaria** [comment]
i guess you didn't get what i want to do, how can i invite the other to
work with me from their machines !

Le ven. 30 août 2019 à 04:04, Takahiro Kubo <notifications@github.com> a
écrit :
