### ISSUE TITLE
Feature request: Multiple labels for same selected text 

### ISSUE THREAD

**Issue by ssadhukha** [chakki-works/doccano#364]
### Problem
In sequence labeling, it would be useful to be able to annotate multiple labels for the same selected/highlighted text. Right now, it is not possible to do this. You cannot select the already labeled/annotated text and then select another label. Theoretically, you could create multiple projects for different types of sequence labelling. Another way to go about it would be to use sequence to sequence labelling and entering your response. However, it would be really convenient to have a feature to do multi-level labelling all at once with sequence labelling. 

![Screen Shot 2019-08-30 at 10 45 44 AM](https://user-images.githubusercontent.com/29761322/64030441-9caeda00-cb14-11e9-871b-16d6554b607e.png)

Here, I cannot select already labelled text, and label as 'anecdote'. 

![Screen Shot 2019-08-30 at 10 52 57 AM](https://user-images.githubusercontent.com/29761322/64030455-9e789d80-cb14-11e9-958a-dfc73c90231a.png)

**Comment by icoxfog417** [comment]
duplicate with #19
