### ISSUE TITLE
UI improvements for prolonged annotation work

### ISSUE THREAD

**Issue by rbagd** [chakki-works/doccano#366]
We ran a `doccano`-based tagging experiment with over a dozen of collaborators who were doing the annotations and got some feedback on the UI that I thought I would share.

Among the feedback that we received was that whenever annotating continues over a longer period of time, `doccano` (default setup) causes somewhat of an eye fatigue. Two main reasons were identified.

* **Font** was tiring and not easy to read. Now that I looked at it in more detail, I kind of agree that the default Arial doesn't look as nice and might not be that easy to read at `16pt`.
* **White background** caused eye-strain after longer periods of annotating documents. Indeed, default white might be somewhat a little too bright.

I think I will adapt the CSS on a local fork for my future experiments but was wondering whether someone with more UI experience can offer his/her input on best CSS values that could improve the default setup as well.

**Comment by icoxfog417** [comment]
Thank you for great feedback! We are willing to incorporate your feedback to the [new UI](https://github.com/chakki-works/doccano/pull/341).

**Comment by icoxfog417** [comment]
Continue on #341.
