### ISSUE TITLE
No response after   upload file !

### ISSUE THREAD

**Issue by zyjcs** [chakki-works/doccano#367]
![8785855746546](https://user-images.githubusercontent.com/18757695/64166171-2d6d1900-ce79-11e9-88a3-6dc755c2599e.png)
![222222222222222](https://user-images.githubusercontent.com/18757695/64166599-006d3600-ce7a-11e9-8e1e-3d41f70f95d3.png)

Ubuntu 16.04 
docker  18.09
no response? I chose a .csv file ，and did not upload successful ,I use docker .

and my data1.csv like this ,i don't know how to upload the data ,i want do a NER annotation。

**Comment by zyjcs** [comment]
![image](https://user-images.githubusercontent.com/18757695/64166856-8d17f400-ce7a-11e9-9f3a-6ccb9946596e.png)

**Comment by zyjcs** [comment]
![image](https://user-images.githubusercontent.com/18757695/64166880-9d2fd380-ce7a-11e9-8ebe-2e9bb22bad6d.png)

**Comment by icoxfog417** [comment]
duplicate post in #323.
