### ISSUE TITLE
Splitting the data-set

### ISSUE THREAD

**Issue by a-shkarupin** [chakki-works/doccano#368]
### System information
- Linux Ubuntu 18.04
- Python Version: 3.6

### Splitting the data-set between multiple annotators
We have a large data-set that needs to be annotated by a few people. Is it currently possible to filter out the documents that were annotated by someone else from a users annotations list? 
The objective is to save time by having each document annotated only once.

Currently we ended up splitting the data-set into several projects and assigning each project to a different person.

Thanks!

**Comment by icoxfog417** [comment]
The most intuitive way has separated the project for each user. Please refer the discussion at #360.
