### ISSUE TITLE
Sequence labeling for documents

### ISSUE THREAD

**Issue by mouthgalya** [chakki-works/doccano#372]
Hi
We would want to import the whole document and file content and assign labels to the document content. Currently doccano automatically parses the input and separates out the individual sentences. Can we instead do sequence labeling at the document level??
MG

**Comment by icoxfog417** [comment]
You can do sequence labeling at the document level. But I recommend separating the document to each sentence to make model training easily.

**Comment by mouthgalya** [comment]
But we are noticing that the document

**Comment by mouthgalya** [comment]
But we are noticing that the document is by default split into lines(because of line feed characters) when we import the data. Is there any way to override this default behavior so that we can see the entire document content in the screen

**Comment by icoxfog417** [comment]
doccano separates each data by line break now. But you can use a hack that replace line break to `\n`. Please refer #330.
