### ISSUE TITLE
Separate labels from projects

### ISSUE THREAD

**Issue by Valtonis** [chakki-works/doccano#377]
Hi. I faced a problem connected with labeling. Imagine you have a big dataset which you want to split into smaller pieces and give it to markup for different people. To do this you always have to make a new project and implement labels (which would be the same as in other projects). If you have a lot of splitted texts it becomes quite tiringly.
So I guess it would be more effective if we could create labels separately and just choosing appropriate label set from projects.

Also, I think same situation could be with texts. So maybe someone could need to markup the same texts with different labels set. In that case more efficient would be to make projects as connections between texts and label sets.

**Comment by icoxfog417** [comment]
Please follow the issue template and refer the related (#360) issue before you raise an issue.
