### ISSUE TITLE
Ids description

### ISSUE THREAD

**Issue by Valtonis** [chakki-works/doccano#378]
We can download JSONL file with markup information but unfortunately, there is some ids used: user id, label id. But there is no convenient way to receive information about user name from user id, label name from label id. But you are adding texts in the result even though there is text id in the result file.
Maybe, it would be more useful to return in JSONL file with markup information only ids but add an opportunity to download another file with information about such connections: 
user id --> user name (for users which participated in a markup of the project)
label id --> label name
text id --> text

**Comment by icoxfog417** [comment]
Please follow the issue template and refer the related (#295) issue before you raise an issue.
