### ISSUE TITLE
Deploy under a subpath

### ISSUE THREAD

**Issue by afausttanasescu** [chakki-works/doccano#380]
We are trying to deploy doccano with a base_uri under www.somesite.com/webapps/doccano. 

We get the django login page, and the login process completes successfully, but static assets don't load. Since the nodejs webapp is packaged as a static asset, it doesn't load either:

```
Loading failed for the <script> with source “https://www.somesite.com/static/bundle/projects.js”.
```
The static asset url should have been translated to https://www.somesite.com/[webapps/doccano/]static/bundle/projects.js

We have tried both removing the base URI (webapps/doccano) as well as leaving it there. We have also tried editing settings.py with :
* FORCE_SCRIPT_NAME = webapps/doccano/ with and without trailing slash
* setting STATIC_URL = webapps/doccano/ with and without trailing slash

@dlevesque-cdpq

**Comment by icoxfog417** [comment]
Did you finally success to deploy doccano under subpath? Anyhow, it'll be Django matter rather than doccano.
