### ISSUE TITLE
Hi I am not able to login to my doccano page. And when i sign up with a new account i am not getting a confirmation mail back.Please help me with this.

### ISSUE THREAD

**Issue by leventm** [chakki-works/doccano#381]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by icoxfog417** [comment]
Please follow the issue template, we can't help you without reproducible procedure and your environment information.
