### ISSUE TITLE
Is it possible to use markdown or any other formatting in the texts to be annotated?

### ISSUE THREAD

**Issue by fhamborg** [chakki-works/doccano#382]
Using the latest doccano version, I am wondering whether I can format the text that is to be shown to the coders doing the labeling work? I'm asking specifically for the *document classification* variant. Is it possible, for instance, to make certain parts bold? 

I tried using HTML markup (`<bold>`) and markdown (`*`)

**Comment by icoxfog417** [comment]
Currently, doccano only supports plain text.

**Comment by amitrecords** [comment]
This would be a good enhancement or feature request though.
