### ISSUE TITLE
Bookmarks/skip forward to next unviewed text

### ISSUE THREAD

**Issue by Zylatis** [chakki-works/doccano#384]
Related to these two issues
https://github.com/chakki-works/doccano/issues/310
https://github.com/chakki-works/doccano/issues/14

It would be great to have the notion of a text having been 'seen' not just annotated and then skip to next 'unseen' (by any annotator on the project, or by given user) bit of text.

The reason is we can have large amounts of text which legitimately have no annotations and I don't want to have to keep going over those, rather I want to sort by ones that have been seen by at least one person.

Thanks,
Z

**Comment by icoxfog417** [comment]
duplicate to #261
