### ISSUE TITLE
Can't remove annotation done by other user when logged in as admin

### ISSUE THREAD

**Issue by Zylatis** [chakki-works/doccano#385]
I attached a normal user to a project and added an annotation which I then cannot seem to remove as admin (it was not yet clicked as approved)

See attached for console log showing the error

![doccano error](https://user-images.githubusercontent.com/1456631/66104925-4a724480-e5fd-11e9-962c-7fef38301cdb.png)

Should the admin user not be able to do this?

**Comment by prokotg** [comment]
I have the same issue

**Comment by DLNSimha** [comment]
> I have the same issue

Same Here
