### ISSUE TITLE
The collision between UI and the Admin panel

### ISSUE THREAD

**Issue by tuyenta** [chakki-works/doccano#387]
Problem
---------
When I created a new project in Doccano by using the Admin panel (Django admin panel), I could not see any (existed) projects in the UI. Then if I delete the created project, then all other projects appear. When I created a new project by UI, everything was fine.

Question
---------
Are there a collision between UI and the Admin panel in order to make a new project?

Environment
---------
*   Operating System: OS Mojave
*   Python Version Used: 3.7
*   How did you install doccano (Heroku button etc): Docker Container

**Comment by icoxfog417** [comment]
Please create the project from the UI. Django admin panel does not guarantee integrity on the doccano.
