### ISSUE TITLE
Docker Compose Bug

### ISSUE THREAD

**Issue by jonhilgart22** [chakki-works/doccano#391]
How to reproduce the behaviour
---------

`docker-compose up`

`django_1    |     In file included from src/buffer.cpp:12:
django_1    |     src/pyodbc.h:56:10: fatal error: sql.h: No such file or directory
django_1    |      #include <sql.h>`

Your Environment
---------

*   Operating System: Mac Mojave 10.14
*   Python Version Used: 3.6
*   When you install doccano: 10/7/19
*   How did you install doccano (Heroku button etc): locally - clone the repo

**Comment by jonhilgart22** [comment]
After rebuilding the image `docker built -t doccano .` and adding the packages below into `install-mysql.sh`, and editing the docker-compose file to use `image: doccano:latest`, it worked.

```# install build dependencies
apt-get update
apt-get install --no-install-recommends -y \
  curl=7.52.1-5+deb9u9 \
  build-essential \
  gnupg=2.1.18-8~deb9u4 \
  apt-transport-https=1.4.9 \
  unixodbc unixodbc-dev python-pyodbc libsqliteodbc```

**Comment by icoxfog417** [comment]
related issue #374 . We have to confirm docker-compose.

**Comment by bensums** [comment]
Same issue. 
* OS: Manjaro.
* Docker version 19.03.1-ce, build 74b1e89e8a
* docker-compose version 1.24.1, build unknown
* Cloned from git (commit 1066c3a)

**Comment by icoxfog417** [comment]
Thank you for your contribution!!
