### ISSUE TITLE
Hard Coded AMI Id in cloudformation template fails

### ISSUE THREAD

**Issue by adamkgray** [chakki-works/doccano#397]
How to reproduce the behaviour
---------
I copied the AWS cloudformation template from the repo and tried to deploy it to my AWS account. It failed because it could not find the AMI.

Your Environment
---------

I am in the ap-east-1 region. This is important because AMIs are local to a region. But I suspect the ami not even exist anymore. Has anyone else tried to deploy the cfn template recently?

Suggestion
---------

Consider using something like this:
https://aws.amazon.com/blogs/compute/query-for-the-latest-amazon-linux-ami-ids-using-aws-systems-manager-parameter-store/

Also, it was doubly frustrating because I could not easily find anywhere in the documentation what image it was using. Just the non-existent AMI id. So I had to guess that you were using ubuntu 16.

**Comment by BrambleXu** [comment]
You should see the repo carefully. The AWS deploy script is already in the repo, [here](https://github.com/chakki-works/doccano/blob/master/awsdeploy.yml).  It assumes the user is in the us-east-1. You can replace the AMI id with the new AMI id in your region.

**Comment by icoxfog417** [comment]
Marge this issue to #400 . @BrambleXu please fix AWS CloudFormation or add tutorial if the script does not matter but the procedure is difficult to understand.

**Comment by BrambleXu** [comment]
@icoxfog417 
I would like to add additional instruction to the [tutorial](https://github.com/chakki-works/doccano/wiki/HTTPS-setting-for-doccano-in-AWS). But I have no authority to modify the wiki page now. Could you add the below content at the start of the [tutorial](https://github.com/chakki-works/doccano/wiki/HTTPS-setting-for-doccano-in-AWS)?

```
# Attention: change AMI ID based on your region

The AWS one-click deployment assumes the user is in the region us-east-1. If you are in another region, you can modify the [awsdeploy.yml](https://github.com/chakki-works/doccano/blob/master/awsdeploy.yml). You should replace the AMI id with the new AMI id in your region.
```

**Comment by icoxfog417** [comment]
Thanks! I edited [tutorial](https://github.com/chakki-works/doccano/wiki/HTTPS-setting-for-doccano-in-AWS#https-settings-for-doccano-in-aws) (I think you can edit).

![image](https://user-images.githubusercontent.com/544269/66909077-1ceab980-f047-11e9-9d5c-411e930a8551.png)

**Comment by BrambleXu** [comment]
@icoxfog417 
Thanks! 
I have the edit right several months ago. But it seems I am no longer a collaborator, so I cannot edit the wiki pages. 
Anyway, thanks for the help.

**Comment by adamkgray** [comment]
Hi all. I am sort of new to open source stuff. But I forked the repo, made some edits and pushed up a new branch for review. It removes the hard-coded ami and fetches it dynamically in the cfn template with a lambda function.

It's here https://github.com/chakki-works/doccano/pull/405

Let me know if I am following the correct procedure here. Just want to help xD
