### ISSUE TITLE
django_heroku is not listed in requirements.txt

### ISSUE THREAD

**Issue by RAJAT--PALIWAL** [chakki-works/doccano#4]
django_heroku is not listed in requirements.txt
So, when running manage.py, script raises error django_heroku module not found.

**Comment by icoxfog417** [comment]
Thank you for reporting. I confirmed `requirements.txt` and it includes `django_heroku`.

https://github.com/chakki-works/doccano/blob/master/requirements.txt#L4

Please check your `pip install` process is correctly executed or virtual environment is activated.
