### ISSUE TITLE
Feature Request: keyboard navigation (next/previous item)

### ISSUE THREAD

**Issue by PanBartosz** [chakki-works/doccano#40]
I could not find any way to navigate between items using keyboard shortcuts. Maybe it is a good idea to add them? For example arrow keys for previous/next document on the list.

**Comment by BrambleXu** [comment]
The shortcut feature is already implemented. You can use three shortcuts to navigate document. Taking the **Next** button as example, you can use `ctrl n`, `'arrowdown'` and `'arrowright'`. Is this helpful?

**Comment by misssprite** [comment]
It will be more convenient to have left-hand navigation shortcuts. This modification makes a more fluent workflow, when working with sequence labeling job. We can keep left hand on keyboard and right hand on mouse selecting texts, without moving around.

Maybe with a custom key config? @BrambleXu
