### ISSUE TITLE
App fails to create on CloudFormation

### ISSUE THREAD

**Issue by marcinic** [chakki-works/doccano#400]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):
I get the following notice when clicking launch on the EC2 Cloudformation script: 
The following resource(s) failed to create: [App]. . Rollback requested by user.
The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request. (Service: AmazonEC2; Status Code: 400; Error Code: VPCResourceNotSpecified; Request ID: 38b35da4-30be-4426-a067-f46730925883)

I think there may be another set of parameters to be specified.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html

**Comment by icoxfog417** [comment]
Please try again #397 is already fixed.
