### ISSUE TITLE
How to save the previously created project

### ISSUE THREAD

**Issue by song-heng** [chakki-works/doccano#404]
Thanks for your nice work. I  install doccano with Option1, and run it by  running the Docker image as a Container. The features of doccano work well, but after restarting my computer and re-running doccano, I find  that the sequence annotation project I created earlier is missing. So, how to  save the previously created project?

**Comment by icoxfog417** [comment]
You can delete project by delete button.

![image](https://user-images.githubusercontent.com/544269/66908909-d72df100-f046-11e9-9698-80ca7f861df1.png)
