### ISSUE TITLE
doccano not working after update

### ISSUE THREAD

**Issue by urigoren** [chakki-works/doccano#406]
How to reproduce the behaviour
---------
I have followed the following steps to update `doccano` :
1. `git pull`, 
1. rebuilt the static  (`npm install; npm run build`)
1. updated `settings.py`  with my server credentials
1. tried `manage.py migrate` and `manage.py makemigrations`

Got this exception:

> 
> Traceback (most recent call last):
>   File "manage.py", line 15, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 375, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 316, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 353, in execute
>     output = self.handle(*args, **options)
>   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 83, in wrapped
>     res = handle_func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/django/core/management/commands/makemigrations.py", line 89, in handle
>     loader = MigrationLoader(None, ignore_no_migrations=True)
>   File "/usr/local/lib/python3.6/dist-packages/django/db/migrations/loader.py", line 49, in __init__
>     self.build_graph()
>   File "/usr/local/lib/python3.6/dist-packages/django/db/migrations/loader.py", line 273, in build_graph
>     raise exc
>   File "/usr/local/lib/python3.6/dist-packages/django/db/migrations/loader.py", line 247, in build_graph
>     self.graph.validate_consistency()
>   File "/usr/local/lib/python3.6/dist-packages/django/db/migrations/graph.py", line 243, in validate_consistency
>     [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
>   File "/usr/local/lib/python3.6/dist-packages/django/db/migrations/graph.py", line 243, in <listcomp>
>     [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
>   File "/usr/local/lib/python3.6/dist-packages/django/db/migrations/graph.py", line 96, in raise_error
>     raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
> django.db.migrations.exceptions.NodeNotFoundError: Migration server.0003_auto_20190708_1208 dependencies reference nonexistent parent node ('server', '0002_project_randomize_document_order')

Your Environment
---------

*   Operating System: Ubuntu 16
*   Python Version Used: 3.6

**Comment by icoxfog417** [comment]
The following would be related. If you have labeled dataset in doccano, I recommend downloading it before the upgrade.

https://stackoverflow.com/questions/33675960/django-migration-error-nodenotfounderror
