### ISSUE TITLE
Unable to import data. Fails with a message "This field is required"

### ISSUE THREAD

**Issue by obai-d** [chakki-works/doccano#408]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/52337213/67153850-cb4c6400-f2be-11e9-81f5-7267c9d48d3d.png">

How to reproduce the behaviour
---------
Create a new project
Import data
Select a JSONL file for upload
You get the above message

Your Environment
---------
Pulled the production docker image chakkiworks/doccano
And ran it locally on a Mac.

**Comment by icoxfog417** [comment]
Could you please provide some lines of your uploaded file?

* Any `.jsonl` file cause this error?
* Did you try other formats (`.csv` etc) ?

**Comment by obai-d** [comment]
@icoxfog417 I was using a `.jsonl` file with single line. Below is its content.
```
{"directions":["Remove foil lid from cake package. (Do not remove cake from pan.) Pierce cake with skewer at 1/2-inch intervals, poking skewer through cake to bottom of pan.","Add boiling water to gelatin mix in small bowl; stir 2 min. until completely dissolved. Stir in cold water; pour over cake. Refrigerate 1 hour. Meanwhile, make curls from semi-sweet chocolate.","Invert cake onto platter. Cut cake horizontally in half. Spread bottom half of cake with 1/3 cup COOL WHIP; cover with 1 cup pie filling and top cake layer. Frost top and sides of cake with remaining COOL WHIP. Garnish with remaining pie filling and chocolate curls."],"ingredients":["1 (16 ounce) loaf frozen pound cake, thawed","3/4 cup boiling water","1 (3 ounce) package JELL-O Cherry Flavor Gelatin","1/4 cup cold water","1 ounce BAKER'S Semi-Sweet Chocolate","2 cups thawed COOL WHIP Whipped Topping, divided","1 1/2 cups cherry pie filling, divided"],"language":"en-US","source":"mysite.com","tags":[],"title":"1-2-3 Cherry Poke Cake","url":"http://mysite.com/recipe/235063/1-2-3-cherry-poke-cake/"}
```

Thanks

**Comment by obai-d** [comment]
> Any .jsonl file cause this error?

Yeah, I tried a simple one  and that also fails with same error `This field is required.`
Content of `.jsonl`
```
{"name":"one","value":"two"}
{"name":"king","value":"queen"}
{"name":"prince","value":"princess"}
```

> Did you try other formats (.csv etc) ?

CSV with above content works. However when I tried a large CSV file it failed with a message about having more than 100 words. Guess there is a limitation on number of words?

**Comment by icoxfog417** [comment]
You have to use `text` and `labels` field in your `.jsonl` file as an example suggests. Please refer the following link.

https://github.com/chakki-works/doccano/wiki/Import-and-Export-File-Formats
