### ISSUE TITLE
Couldn't login

### ISSUE THREAD

**Issue by hpeiyan** [chakki-works/doccano#411]
How to reproduce the behaviour
---------

I have pulled the project in the past 3 months, and today I run the docker server, I didn't remember the username and password. After I sign up again, I couldn't log in anymore.
Thanks for helping!
![image](https://user-images.githubusercontent.com/12880598/67194692-2fd80200-f42a-11e9-923c-7a4530c53ab2.png)

Your Environment
---------

*   Operating System: Mac OS
*   Python Version Used: 3.6
*   When you install doccano: 3 months ago
*   How did you install doccano (Heroku button etc): docker

**Comment by icoxfog417** [comment]
Please use [Django Admin page](https://djangobook.com/mdj2-django-admin/) or re-install doccano.

**Comment by hpeiyan** [comment]
Thank you
