### ISSUE TITLE
Couldn't Filter documents

### ISSUE THREAD

**Issue by hpeiyan** [chakki-works/doccano#414]
How to reproduce the behaviour
---------

Hi, there. 
Thanks for your job. We have three accounts to collabrate, I found the 'Active' and 'Complete' Filter didn't work, except the admin. 
Or I have to set something?
Thanks for helping.

![image](https://user-images.githubusercontent.com/12880598/67352457-9f610500-f582-11e9-824a-ca879b6a181a.png)

Your Environment
---------

*   Operating System: Mac OS
*   Python Version Used: 3.6
*   When you install doccano: 3 days ago
*   How did you install doccano (Heroku button etc): Docker with my CentOS server

**Comment by emilymacleod** [comment]
I'm also having issues with Doccano's search function. If any amount of annotations have been done, and then someone does a keyword search, it's hard to find where the returned results are down the bottom. You need to scroll through thousands of documents to get back to 1 and sometimes the text isn't there. 

Any news on this?

**Comment by icoxfog417** [comment]
Please update to latest doccano. The user interface is drastically changed.
