### ISSUE TITLE
`api` prefix instead of `server` prefix, caused migration to fail

### ISSUE THREAD

**Issue by urigoren** [chakki-works/doccano#415]
How to reproduce the behaviour
---------
After upgrading `doccano`, and applying the appropriate migrations, I saw that the projects and annotactions are empty.

looking at the DB, I saw that the data is there, but all the tables are duplicated. the older version has the `server_` prefix, and the newer version has the `api_` prefix, see screenshot:

![Screen Shot 2019-10-23 at 13 07 47](https://user-images.githubusercontent.com/6126173/67382541-50bd6600-f596-11e9-8e9a-760c3522cdbe.png)

After digging in the commit history, I noticed this commit:
https://github.com/chakki-works/doccano/commit/8713a281d9eeb968d986f68d2c313fd0b033c646#diff-124a6ba15fec243ecdee19459cd8f687

That manually changes `server` to `api`, (why ?), how do I migrate my data to the new structure ?

Your Environment
---------

*   Operating System: Ubuntu 16
*   Python Version Used: 3.6

**Comment by urigoren** [comment]
@icoxfog417 , why is this marked as question and not a bug ?

After upgrading `doccano`, all the previous projects and annotations became unaccessible.

Sounds like a bug to me

**Comment by icoxfog417** [comment]
doccano does not support backward compatibility yet. If you want to keep your annotation result, please download data => upgrade doccano => import downloaded data.
