### ISSUE TITLE
Deploying to Azure

### ISSUE THREAD

**Issue by rebby123** [chakki-works/doccano#416]
How to reproduce the problem
---------

I have attempted to deploy docanno to azure. I have a free subscription with azure, and I fill out the form to include my app name, secret key, resource group name, admin password etc. Unfortunately this deploys unsuccessfully.

I am new to azure and docanno and would appreciate any help. I have also tried to deploy from here: https://github.com/aribornstein/doccano4Azure?source=post_page-----b29f479c0c54----------------------

however, whilst this seems to deploy my password and username do not work when i get to the log in page.

Any help greatly appreciated.

```bash
Deployment to resource group 'DocannoResources' failed.
Additional details from the underlying API that might be helpful: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
```

Your Environment
---------

*   Operating System: Windows 10 Enterprise
*   Python Version Used:
*   When you install doccano: 23/10/2019
*   How did you install doccano (Heroku button etc): Azure button

**Comment by c-w** [comment]
Could you confirm that your password contains no special characters? See https://github.com/chakki-works/doccano/issues/325 and https://github.com/chakki-works/doccano/issues/248 for discussions of similar problems.

**Comment by rebby123** [comment]
Yep, no special characters

**Comment by c-w** [comment]
Unfortunately I'm unable to reproduce this problem using the "Deploy to Azure" button in the README (note that the doccano4Azure repository is deprecated given that doccano now has upstream support for Azure).

I used a password and secret key generated by `< /dev/urandom tr -dc '_A-Z-a-z-0-9' | head -c32` which led to a working deployment for me. Could you provide the deployment details for the failed deployment to help me investigate?

![Screenshot showing ARM deployment details](https://user-images.githubusercontent.com/1086421/67581176-92284f80-f715-11e9-8a9e-e8b719bf06a1.png)
