### ISSUE TITLE
WebpackError when building service from docker-compose

### ISSUE THREAD

**Issue by 0lucasmoura** [chakki-works/doccano#419]
How to reproduce the problem
---------

I have cloned the repo from master (commit 59b8564) and after building the service using _docker-compose up_ and trying to acces the web page on localhost:8000, it threw this error.

![image](https://user-images.githubusercontent.com/41756629/67488209-ca605d00-f645-11e9-9de8-a007967c82be.png)

I have little understanding on Node.js and Django but I believe that this dependency was forgotten somewhere on the requirements. Yesterday I had made the same installation procedure and it worked fine, so it might be a problem that rose after the last PR.

```bash
WebpackError at /

            ModuleNotFoundError in 
            Module not found: Error: Can't resolve 'buefy' in '/src/app/server/static/pages'
            
```

Your Environment
---------

*   Operating System: Ubuntu 18.04
*   Python Version Used: python 3.6.8
*   When you install doccano: Thursday 24 2019
*   How did you install doccano (Heroku button etc): Pull the repo and docker-compose up

**Comment by c-w** [comment]
The dependency is included in package.json [here](https://github.com/chakki-works/doccano/blob/59b8564c14490d00e1c6af80a343c9d9932b9817/app/server/static/package.json#L19).

To improve performance of the docker-compose setup, we're currently caching the node_modules in a volume ([see code](https://github.com/chakki-works/doccano/blob/59b8564c14490d00e1c6af80a343c9d9932b9817/docker-compose.yml#L23)). This means that whenever there's a dependency change, you need to run `docker-compose down --volumes` and then restart the docker-compose stack as normal via `docker-compose up`.

Let me know if this fixes your problem!

**Comment by 0lucasmoura** [comment]
I have deleted the corresponding images and containers and then rebuilt everything from ground and it worked! Thanks!
