### ISSUE TITLE
Add the date/time column to annotation table to track annotation speed etc.

### ISSUE THREAD

**Issue by kencoken** [chakki-works/doccano#42]
Currently the database schema for labels does not track when labels are added:
```
sqlite> .schema server_sequenceannotation
CREATE TABLE "server_sequenceannotation" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "prob" real NOT NULL, "manual" bool NOT NULL, "start_offset" integer NOT NULL, "end_offset" integer NOT NULL, "document_id" integer NOT NULL REFERENCES "server_document" ("id") DEFERRABLE INITIALLY DEFERRED, "label_id" integer NOT NULL REFERENCES "server_label" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "server_sequenceannotation_document_id_e1057912" ON "server_sequenceannotation" ("document_id");
CREATE INDEX "server_sequenceannotation_label_id_05d8e2eb" ON "server_sequenceannotation" ("label_id");
CREATE INDEX "server_sequenceannotation_user_id_713fbc2e" ON "server_sequenceannotation" ("user_id");
CREATE UNIQUE INDEX server_sequenceannotation_document_id_user_id_label_id_start_offset_end_offset_b8cc1717_uniq ON "server_sequenceannotation" ("document_id", "user_id", "label_id", "start_offset", "end_offset");
```
In order to track the speed at which labelling is completed, and compare performance of different labellers on the platform, it would be very useful for the date + time a label was created to be stored in the database (and ideally surfaced in the 'statistics' page of a project).

**Comment by BrambleXu** [comment]
Hi, @kencoken. Do you use doccano as admin user and assign tasks to other normal users (labellers)? If so, did you encounter this issue #38 ?

**Comment by icoxfog417** [comment]
I changed the title to clarify the request for this issue.

**Comment by c-w** [comment]
I believe the backend/data for this feature is already implemented. Take a look at the Annotation base model which includes both `created_at` and `updated_at` columns:

https://github.com/chakki-works/doccano/blob/61c50699348321db7a26f8df5b80706c2c5390a6/app/server/models.py#L186

I've also verified that these fields are set properly in the underlying Database:

![Screenshot showing Doccano database with annotation created_at column](https://user-images.githubusercontent.com/1086421/54799781-f7263f00-4c34-11e9-8f61-3d162c58182c.png)

It should be possible to surface basic annotator speed statistics based on this information, e.g. for example by comparing the average time between the created_at time for label N and the created_at time for label N+1. Sample naive query:

```sql
select cast((julianday(b.created_at) - julianday(a.created_at)) * 24 * 60 * 60 as integer)
from server_documentannotation a
join server_documentannotation b
on a.id = b.id-1
```

**Comment by BFPLima** [comment]
I almost opened my issue: 

Record each annotation time for further analysis. 
This feature is to intent to record annotation time for each annotation to make some analisis like as: 

* Total project annotation time
* Annotation time user in a project
* Avarage by user
* Etc...

I think this is similar that I realized. Is that correct?

Thanks!

**Comment by c-w** [comment]
@BFPLima It should already be possible to pull most of those datapoints out of the existing database with some SQL queries.

I wonder if it would be worth starting a Grafana dashboard project (or similar) for Doccano so that we can move all the statistics and metrics into a separate tool and don't have to implement them all in Vue. This would also allow to simplify the code and remove the statistics tab. Thoughts @Hironsan?

**Comment by icoxfog417** [comment]
Continue on #114
