### ISSUE TITLE
Doccano claims upload is blank

### ISSUE THREAD

**Issue by Zylatis** [chakki-works/doccano#420]
Hi I am trying to upload plain text but the uploader says 'this cannot be blank' despite the file field and file definitely not being empty
![blank](https://user-images.githubusercontent.com/1456631/67547974-4c3aae00-f74c-11e9-975c-45e255da27c9.png)

**Comment by c-w** [comment]
Possibly related issue: https://github.com/chakki-works/doccano/issues/168

**Comment by icoxfog417** [comment]
And related to #408 . Please check the previous issues.
