### ISSUE TITLE
Problem of signing up

### ISSUE THREAD

**Issue by chiangyulun0914** [chakki-works/doccano#427]
I pulled the production docker image
```
docker pull chakkiworks/doccano
```
and then run the docker with command below
```
docker run -d --rm --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=admin@example.com" \
  -e "ADMIN_PASSWORD=password" \
  -e "ALLOW_SIGNUP=True" \
  -p 8000:8000 chakkiworks/doccano
```

and when I want to add another users, rather than admin, I need to sign up. 
But I find some problems:

![image](https://user-images.githubusercontent.com/36063123/67838192-b330dc00-fb2b-11e9-93f3-9c0efe1f960a.png)

How to solve it ?  
Thanks

**Comment by icoxfog417** [comment]
Please confirm FAQ before you raise an issue and follow the issue template.

https://github.com/chakki-works/doccano/wiki/Frequently-Asked-Questions#i-want-to-add-annotators
