### ISSUE TITLE
Within text formatting for annotation

### ISSUE THREAD

**Issue by AVajpayeeJr** [chakki-works/doccano#428]
I wished to annotate for a structured text format containing two distinct sections that need to be visually separated, in my case a binary document classification for text containing a question and answer. Is there a simple way to include basic formatting (line breaks / bold / html) within the text field of uploaded datasets to annotate?

**Comment by ice3** [comment]
Hello, did you succeed to format the annotation ?

**Comment by kechan** [comment]
I have the same question too. I want to highlight certain substring as red to try to direct human attention.
Wonder if it is possible.

**Comment by david-engelmann** [comment]
> I have the same question too. I want to highlight certain substring as red to try to direct human attention. Wonder if it is possible.

@kechan Were you able to make any progress on this?
