### ISSUE TITLE
Within text formatting 

### ISSUE THREAD

**Issue by AVajpayeeJr** [chakki-works/doccano#429]
Hi,

Is there a simple way of including basic text formatting for text to be annotated? My use case is to annotate for binary classification of a structured text containing 2 sections (a question and its answer ... both of which may contain several sentences) and these two sections should be visually separated. How can we embed HTML in the text field of the dataset to be annotated?

Your Environment
---------

*   Operating System:  MacOS
*   Python Version Used: 3.6
*   When you install doccano: 5 days ago
*   How did you install doccano (Heroku button etc): Docker

**Comment by icoxfog417** [comment]
It is discussed at #382.
