### ISSUE TITLE
Projects are not listed in the Ui

### ISSUE THREAD

**Issue by adamshamsudeen** [chakki-works/doccano#431]
I deployed the latest docker image and got this error. The project page is not getting populated.

<img width="974" alt="Screenshot 2019-10-31 at 1 26 47 PM" src="https://user-images.githubusercontent.com/13180406/67929035-622fef00-fbe2-11e9-9c68-46831641e022.png">

**Comment by icoxfog417** [comment]
Please follow the ISSUE_TEMPLATE. We can't help you without your environment information.
