### ISSUE TITLE
Enable edit while annotating

### ISSUE THREAD

**Issue by Sunnycheey** [chakki-works/doccano#433]
Feature description
---------
Since the dataset get from web is always dirty, so It's maybe better to enable us to correct the content of data while annotating data.

**Comment by Hironsan** [comment]
I'm developing new UI in [dev-frontend](https://github.com/chakki-works/doccano/tree/dev-frontend) branch. It enable us to edit the dataset:

![image](https://user-images.githubusercontent.com/6737785/68121531-5e39ff00-ff4b-11e9-9f6b-b9e882927a25.png)

**Comment by Sunnycheey** [comment]
Appreciate for your awesome work.
