### ISSUE TITLE
auto export annotated data

### ISSUE THREAD

**Issue by Sunnycheey** [chakki-works/doccano#437]
Feature description
---------
I have annotate about 100+ sample in server, and then my peer has just reboot the server without notify me.....

As a result, I can't find any annotated data in my server, does doccano had already store annotated data in somewhere (That will be apperaciated), or does the doccano support auto export?

Willing to get reply.

**Comment by icoxfog417** [comment]
This does not feature request. Please follow ISSUE_TEMPLATE if you describe the faced phenomenon.

**Comment by Sunnycheey** [comment]
Sorry for mismatching _feature request_ . In case of someone encounter the same problem with me, I'd like to leave a comment that when depolying _doccano_ with docker (option 1), you can use [volume](https://docs.docker.com/storage/volumes/) to make data persist (otherwise data will be removed once the container has quitted)

**Comment by icoxfog417** [comment]
I understood your situation. I understood your situation. We consider to add description about attaching the volume to Docker container to avoid data vanishing.
