### ISSUE TITLE
Webpage not loading for creating project.

### ISSUE THREAD

**Issue by ravi0912** [chakki-works/doccano#439]
---------

Hi,
I have followed all the steps mentioned in the documentation.
Installation: option 2
Usage: option 2

```bash
# I'm not getting any error messages.
```

Your Environment
---------

*   Operating System: ubuntu 18.04
*   Python Version Used: 3.6+
*   When you install doccano: today
<img width="1671" alt="Screenshot 2019-11-11 at 3 43 38 PM" src="https://user-images.githubusercontent.com/9092285/68579562-6be70b80-049a-11ea-90db-a80ec53b50e9.png">

*   How did you install doccano (Heroku button etc): manually using option 2.

**Comment by ravi0912** [comment]
Except for the doccano button and login page, all other buttons or links are not loading.

**Comment by c-w** [comment]
@ravi0912 this screenshot looks to me like webpack isn't running. You can verify that this is the problem by checking the network tab on the devtools; I'm assuming that the `projects.js` file isn't being loaded (error 404).

Could you ensure that the following steps have been executed?

```sh
cd app/server/static
npm install
npm start
```

**Comment by ravi0912** [comment]
> @ravi0912 this screenshot looks to me like webpack isn't running. You can verify that this is the problem by checking the network tab on the devtools; I'm assuming that the `projects.js` file isn't being loaded (error 404).
> 
> Could you ensure that the following steps have been executed?
> 
> ```shell
> cd app/server/static
> npm install
> npm start
> ```

**Comment by ravi0912** [comment]
Hi @icoxfog417,
webpack is running. the problem is after login it directs to http://127.0.0.1:8080/projects.js file but it should direct to my <ip-address>:8080/projects.js  not localhost.

**Comment by c-w** [comment]
If you need webpack to serve output on an endpoint other than `127.0.0.1:8080`, you can configure this via the `WEBPACK_HOST` and `WEBPACK_PORT` environment variables ([see webpack.config.js](https://github.com/chakki-works/doccano/blob/da8534d7819c37af5629ce45298efcc80e414afc/app/server/static/webpack.config.js#L11-L12)).

**Comment by ravi0912** [comment]
Thanks @c-w
