### ISSUE TITLE
Project sharing across all users not working

### ISSUE THREAD

**Issue by chaitu0788** [chakki-works/doccano#440]
How to reproduce the behaviour
---------
When I create a project and check the box to share the project across all users, I am not able to see the project in other users' accounts ( I am able to see it only in the admin account).

Your Environment
---------
*   Operating System:Ubuntu 18.04
*   Python Version Used: 3.7
*   When you install doccano: Last Week
*   How did you install doccano (Heroku button etc): Git Clone

**Comment by c-w** [comment]
The "share annotations across all users" checkbox is intended to enable multiple users in the same project to see the same annotations, not for multiple users to see the same project. To share the same project across multiple users, you can invite the user to the project using the "users" tab in the project admin area:

![Screenshot showing user management page in Doccano](https://user-images.githubusercontent.com/1086421/68624319-89b96e00-04a4-11ea-9593-ed9582e84088.png)
