### ISSUE TITLE
how could i add new user ?

### ISSUE THREAD

**Issue by Irvinghua** [chakki-works/doccano#442]
I take option 1 to complete installation(docker pull,docker run).
After successfully run the web application,and i create new project.
But when i want to add new user ,i got this 
![image](https://user-images.githubusercontent.com/2010962/69021414-b1538d80-09f2-11ea-837b-899d7d9d3a3b.png)

I cant add a new user,how i can solve this problem  ?thank you

**Comment by Hironsan** [comment]
Please check the following tutorial:

* https://github.com/chakki-works/doccano/wiki/Frequently-Asked-Questions#i-want-to-add-annotators

**Comment by JamesDConley** [comment]
This section no longer seems to exist, is it still possible to add more annotators?

**Comment by bitmman** [comment]
Same question as @JamesDConley  here.

**Comment by JadenisJelu** [comment]
Visiting the admin site at: {your-url}/admin/ and add users at "authentication and authorization", hope this helps
