### ISSUE TITLE
"Create Project" results in 403 Forbidden

### ISSUE THREAD

**Issue by afparsons** [chakki-works/doccano#444]
Resolved
----------
Team miscommunication. DNS changed between deployment and usage. Resolved.

---

Problem
---------
```bash
POST https://doccano.example.com/v1/projects 403 Forbidden
```

Your Environment
---------
*   Operating System: Ubuntu 16.04.6 LTS
*   Python Version Used: 3.6.9
*   When you install doccano: November 2019
*   How did you install doccano (Heroku button etc): Cloudformation
----------------------

We are able to log into the application (on something akin to doccano.example.com). Under `/projects/`, we can see the greeting banner, the teal project creation button, and "0 projects" listed. 

Our issue begins when we try to create a new project. We can see the modal window where a user enters the project name, description, type, and can check the option boxes. However, clicking "Create" results in a 403 Forbidden error visible in the browser console. No visible changes are propagated in the Doccano GUI.

The README.md lists the following steps with screenshots:

* Confirm all doccano services are running
* Create a project

but does not provide information on troubleshooting should something not function as expected.

We might have something incorrectly configured, but we are unsure of where to look and what to adjust. We can post configs and logs as needed. Thank you in advance.

---

`$ sudo docker inspect doccano`

```
"Image": "chakkiworks/doccano:latest"
```

**Comment by oplatek** [comment]
How did you debug the problem?

I have the same problem but probably a different cause.
Thank you for any help.

**Comment by afparsons** [comment]
@oplatek I'm so sorry, but I don't remember! This was from three years ago and I don't even recall filing this issue. Best of luck in resolving your problem.
