### ISSUE TITLE
Network is unreachable when signup

### ISSUE THREAD

**Issue by lan2720** [chakki-works/doccano#446]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System: redhat
*   Python Version Used: docker
*   When you install doccano: 2019.11.18
*   How did you install doccano (Heroku button etc): docker

![error_signup.png](http://ww1.sinaimg.cn/large/901f9a6fgy1g93l3c4rk2j20kr0qbgpc.jpg)

I am new for this project. Anyone know how to fix this issue?

**Comment by icoxfog417** [comment]
This error seems not doccano's matter. It depends on your network environment.
Please confirm your network/firewall setting.
