### ISSUE TITLE
Enhancement/need to clean dependencies

### ISSUE THREAD

**Issue by Hironsan** [chakki-works/doccano#449]
# Suggestion

* Clean dependencies

# Problem

First of all, doccano includes some unused dependencies. As reported in #447, there was a security vulnerability in Tornado 5.0.2. But in fact, doccano is not using Tornado. The reason that Tornado was included in the dependency is I was trying to implement doccano using Tornado in [early commits](https://github.com/chakki-works/doccano/commit/97e426e1c09a76f0ec20eb658838e6a4a3b2c3d3). In the end, I decided to use Django instead of Tornado. 

# Solution

Remove the following dependencies:

* mixer
* tornado

Actually, I want to manage dependencies with Pipenv, but this is another issue.

**Comment by jonhilgart22** [comment]
Have you considered poetry for package management?

[https://poetry.eustace.io/](https://poetry.eustace.io/)

**Comment by Hironsan** [comment]
I have no idea about poetry so I would like you to tell me which aspects poetry is better than Pipenv?

**Comment by jonhilgart22** [comment]
It supports entrypoints, isort tools. However, it is still pretty new so may not be supported by all packages yet.

**Comment by Hironsan** [comment]
Hmm, ok. Thank you for the information!
I will make a decision after comparing them.
