### ISSUE TITLE
user conventions

### ISSUE THREAD

**Issue by yaojianannan** [chakki-works/doccano#451]
I see that there is no user role convention in readme，So I want to know what are the conventions of the three roles of the user?

**Comment by icoxfog417** [comment]
Related to #445

**Comment by icoxfog417** [comment]
![image](https://user-images.githubusercontent.com/544269/69230166-1ca38800-0bca-11ea-8a6f-897949c39032.png)

**Comment by yaojianannan** [comment]
thank you！
