### ISSUE TITLE
Shortuct keys are not working for text classification

### ISSUE THREAD

**Issue by mathrb** [chakki-works/doccano#453]
Hello,

First of all, great work!

I noticed a difference on text classification between the online demo (previous dashboard) and last release demo (new dashboard). The shortcuts are not working anymore, pressing N or P key does not change the label (Sentiment Analysis project). The arrow keys to navigate between documents work.

Not familiar with Vue.js, can't figure where this is happening.

Have you experienced the same behabior?

King regards

EDIT: I tried using Firefox 70 & chrome 78

**Comment by Hironsan** [comment]
I confirmed the problem. I will add it taks list.
Thanks!

**Comment by Jiaxin-Pei** [comment]
Facing the same issue!

**Comment by mathrb** [comment]
Hello Hironsan,

It is now working !

On the Sentiment Analysis demo page, there's no shortcut key, would be nice for testing purpose :)

Kind regards
