### ISSUE TITLE
Usage Problem

### ISSUE THREAD

**Issue by attenton** [chakki-works/doccano#457]
Please modify the Usage
```bash
docker run -d --rm --name doccano \
   -e "ADMIN_USERNAME=admin" \
   -e "ADMIN_EMAIL=admin@example.com" \
   -e "ADMIN_PASSWORD=password" \
   -p 8000:8000 chakkiworks/doccano
```
Because of the command`docker run -d -rm` which makes the container removed when it is stoped by non-human factors, my data in the container was removed either owing to a power cut-off.
So first, does there exist some way to restroe it, second, please modify it in case someone else meet it.

**Comment by Hironsan** [comment]
We are currently working on this PR https://github.com/chakki-works/doccano/pull/441.
After merging it, we can restore the data.

In addition, I recommend that you should use docker-compose version. The docker version is somewhat old.
