### ISSUE TITLE
Download labeled data doesn't work (on Heroku)

### ISSUE THREAD

**Issue by TheJurgen** [chakki-works/doccano#459]
Hello all,

I'm using doccano on Heroku. 
Lately I've had a lot of problems when trying to download my labeled data. Most of the times when I click the button "Download" (in both situations: CSV or JSONL) it appears that it's loading but then nothing happens. My data isn't downloaded.

It only happens once in many attempts that the labeled data is actualy downloaded. I need to be very lucky and keep trying (almost like playing the lottery) to be able to download my data. My operating system is Windows 10. 

Any help would be grealy appreciated. 

* EDIT: 
- Downloading the labeled data from a mini-project with just over 200 annotated sentences seems to work perfectly.
- Downloading the labeled data from a project with over 10 000 paragraphs, which are only partly annotated gives me issues.

**Comment by icoxfog417** [comment]
It depends your Heroku dyno spec. doccano has memory issue when downloading the labels. We are dealing with it (#383).

**Comment by Hironsan** [comment]
Probably, the timeout value is small.
