### ISSUE TITLE
How to display the extra key-value?

### ISSUE THREAD

**Issue by attenton** [chakki-works/doccano#462]
In the demo website, the key-value can be displayed on the right at the annotation page.

however, when I upload the data with extra key-value  in a json file, the text can be shown correctly, the key-value is still `No data available`

how to display the key-value? does it require special key?

**Comment by Hironsan** [comment]
You probably need `meta` key:

```
{"text": "example", "meta": {"wikiPageID": 1}}
{"text": "example", "meta": {"wikiPageID": 2}}
{"text": "example", "meta": {"wikiPageID": 3}}
```
