### ISSUE TITLE
Auto-labeling feature. Is it available?

### ISSUE THREAD

**Issue by vcjob** [chakki-works/doccano#467]
Hello everyone!

I just saw self-advertisement in the doccano web-app saying _"Auto labeling
Auto labeling is one of the most powerful tools in creating annotated corpora. Machine learning model automatically annotates texts. You're only required to correct a few error annotations."_
I don't see how to turn it on, though. I found issue #412 , but according to that, the feature failed in tests. 
Is this useful feature available, or not?

Thank you!

**Comment by icoxfog417** [comment]
discussed at #191
