### ISSUE TITLE
How to customize Seq labeling interface

### ISSUE THREAD

**Issue by vcjob** [chakki-works/doccano#468]
Hello everyone!

On this GitHub main page (https://github.com/chakki-works/doccano) there is a gif - demo how the system works. In that gif, the interface for sequence labeling  (NER) differs from the default available  in the interface for annotators (as well as in the DEMO at http://doccano.herokuapp.com/).
I think that when each label has its name in the text it looks better and allows for avoiding extra mistakes. How do I do such a feature in the interface for annotators?

Thank you a lot!
![image](https://user-images.githubusercontent.com/51916323/69610482-f607a600-103c-11ea-9ed2-7cb373ca3a36.png)

**Comment by Hironsan** [comment]
Hello @vcjob.

The new interface is available after v1.0.0.
You can use v1.0.0 by running a docker-compose version.
Docker version is previous interface.

# v1.0.0
![](https://github.com/chakki-works/doccano/blob/master/docs/demo_ner.png?raw=true)

# Before v1.0.0
![](https://github.com/chakki-works/doccano/blob/master/docs/named_entity_recognition.png?raw=true)

**Comment by abushoeb** [comment]
Hello @Hironsan, is it possible to use a custom user interface for labeling only? I was looking into this https://github.com/doccano/doccano/tree/master/frontend/layouts, and not sure if this is the right place to begin with. Thank you!
