### ISSUE TITLE
Wrong highlighting when there are overlapping entities in the source data

### ISSUE THREAD

**Issue by greav** [chakki-works/doccano#475]
Hi everyone. 
I have some french data which are already annotated and which I would like an annotator to check, but this data have overlapping entities. For example:
```json
{
	"text": "Les obligations en matière d’autorisation pour les sources de rayonnements ionisants sont définies dans la norme CNEN NE 6.02 . Celle ci classe les sources de rayonnement en 10 catégories : les groupes I à III couvrent les sources scellées , les groupes IV à VIII les sources non scellées de différents types et les groupes IX et X les installations qui utilisent des accélérateurs de particules .", 
	"labels": [
		[62, 84, "11 Occupational Health"], 
		[62, 73, "11 Occupational Health"], 
		[159, 170, "11 Occupational Health"]
	]
}
```
So, the first entity is `"rayonnements ionisants"` and the second one is `"rayonnement"`. The problem is that when I try to highlight an entity after these overlapping entities I higlight totally incorrect words. For example, I tried to highlight `dans la norme` but it highligted `6.02 . Celle` (see gif below).
![bug](https://user-images.githubusercontent.com/32651336/69724933-09df0500-112e-11ea-85aa-1106940697b1.gif)

Moreover, you can see that it duplicates `"rayonnements ionisants"` because of overlapping entities. I suppose that's why it highlights wrong words.

**Comment by Hironsan** [comment]
Hello, @greav.
Thank you for your question.

Actually, doccano doesn't support overlapping entities.
The specification is as follows:

* We can annotate text without overlapping.
* We cannot annotate text with overlapping.
* But we can import text with overlapping entities. (← known bug)

Sorry for the inconvenience.
