### ISSUE TITLE
Why are the annotation page for document classification built from docker-compose and docker different?

### ISSUE THREAD

**Issue by Jiaxin-Pei** [chakki-works/doccano#476]
Hello, if the website is built using docker-compose, the document classification page doesn't support shortkey, but it does so when it was built from docker, why?

(![image](https://user-images.githubusercontent.com/42936410/69729514-73422200-10f4-11ea-9f2f-172a832788a9.png))
![image](https://user-images.githubusercontent.com/42936410/69729575-8d7c0000-10f4-11ea-94b2-de2dc3775473.png)

Were the images pulled from chakkiworks/doccano built from other source codes different from the current master branch?

**Comment by Hironsan** [comment]
Hello,

> the document classification page doesn't support shortkey

It has already solved in https://github.com/chakki-works/doccano/issues/453.

> Were the images pulled from chakkiworks/doccano built from other source codes different from the current master branch?

We released v1.0.0 two weeks ago.
Docker compose uses v.1.0.0 but Docker uses previous version.
That's why the interface is different.

We are planning to change the interface in Docker version. Please wait.
