### ISSUE TITLE
can't annotate after uploading the dataset

### ISSUE THREAD

**Issue by xuanlv2** [chakki-works/doccano#48]
If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.

------------------------

### System information
- Windows 10
- Python 3.6.5

### Describe the problem
For text classification, after I uploaded the text documents and defined the labels per the instruction, I clicked the annotate data tab, but it only showed an empty page, any clues what went wrong?

### Source code / logs
This is a snapshot of what is shown when I clicked annotate data tab
![image](https://user-images.githubusercontent.com/4184446/50306539-de569380-0463-11e9-85fc-e556dccdabfd.png)

**Comment by icoxfog417** [comment]
Thank you for reporting the issue.

I confirmed doccano on Windows 10 & Python 3.6.4 it works fine (version is 
 a little different but it may not affect phenomenon).

If you don't have any data, you can confirm your label like following.

![image](https://user-images.githubusercontent.com/544269/50315423-11e1fe00-04f6-11e9-9800-58df7a5cfa8e.png)

1. Do you use `master` branch?
2. Can you confirm your data at `Dataset` page on your project?
3. Can you confirm your label at `Labels` page on your project?

**Comment by xuanlv2** [comment]
> Thank you for reporting the issue.
> 
> I confirmed doccano on Windows 10 & Python 3.6.4 it works fine (version is
> a little different but it may not affect phenomenon).
> 
> If you don't have any data, you can confirm your label like following.
> 
> ![image](https://user-images.githubusercontent.com/544269/50315423-11e1fe00-04f6-11e9-9800-58df7a5cfa8e.png)
> 
> 1. Do you use `master` branch?
> 2. Can you confirm your data at `Dataset` page on your project?
> 3. Can you confirm your label at `Labels` page on your project?
> 4. Can you provide samples of your uploaded data?

Thank you for your reply!
1. Yes,
2,3 Below are the screenshots of the Dataset and Labels page:
![image](https://user-images.githubusercontent.com/4184446/50316549-26d27900-0485-11e9-9fdb-cb72851c4c4c.png)
![image](https://user-images.githubusercontent.com/4184446/50316578-394cb280-0485-11e9-87e4-b39d2fbdc705.png)
4. Yes, here is the text file I used
[Test.txt](https://github.com/chakki-works/doccano/files/2700972/Test.txt)

**Comment by icoxfog417** [comment]
Thank you for your environment information!

I can setup the project by your data.

![image](https://user-images.githubusercontent.com/544269/50320387-73629680-050f-11e9-95db-904e09929673.png)

You use doccano at offline environment? `doccano` uses internet connection to load Javascript / CSS files.

**Comment by xuanlv2** [comment]
Thank you for your reply!
I do not use it at offline environment, the internet connection is always on. 
Could it be the browser's problem? 
I tried to play with the live demo, but it also gave me the similar empty page.

**Comment by icoxfog417** [comment]
Can you use Google Chrome? We mainly use Chrome for developing the doccano.

**Comment by xuanlv2** [comment]
I am actually using Google Chrome.
When I refresh the annotation page, the contents blinks for like a second, and then disappear.

**Comment by icoxfog417** [comment]
Oh, it's odd situation. Could you show us the Chrome console message (like #49)? JavaScript error would be logged there.

**Comment by xuanlv2** [comment]
That's the error message when I was trying to check the demo:
![image](https://user-images.githubusercontent.com/4184446/50324948-bee55800-04af-11e9-83e6-f11079760440.png)

**Comment by BrambleXu** [comment]
@xuanlv2 @huojianzhatian 
After you create a project, upload data, create labels, you can just click 'Annotate data' button to the annotation page.
The error you meet is because you click the 'Try Demo' button in the homepage (click doccano icon in the top left corner), and this is only for demonstration. If you are on the homepage, you should click the 'Project' button in the top right corner. You should find the project you created and click the project name to start annotation.

**Comment by Xinyi2016** [comment]
@xuanlv2 @huojianzhatian 
I got the same problem. Here is a quick fix by replacing

`<script src="https://unpkg.com/marked@0.3.6"></script>
<script src="https://unpkg.com/lodash@4.16.0"></script>
`
in the file `app\server\templates\annotation\annotation_base.html`

with the following paths:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.5.2/marked.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.js"></script>`

After that, the annotation works well for me. 

I made a pull request to fix this bug. Please let me know if you have further issues.

**Comment by BrambleXu** [comment]
Hi @Xinyi2016, thanks to your update. Did you know why this bug occur? It is really wired that we can not reimplement this bug.

**Comment by huojianzhatian** [comment]
@Xinyi2016  Thanks a lot, the annotation works well for me then.

**Comment by huojianzhatian** [comment]
@BrambleXu Thanks!

**Comment by BrambleXu** [comment]
@Xinyi2016 Yes. I tired incognito window and it worked fine.

**Comment by icoxfog417** [comment]
I can get status `200` from `https://unpkg.com/marked@0.3.6` by `curl` script. So browser cache seems to be not cause. But it will be good to describe until `*.js` file.

@Xinyi2016 , @xuanlv2 , @huojianzhatian , would you  confirm below fix is effective to load annotation page, please?

**Before**

```
<script src="https://unpkg.com/marked@0.3.6"></script>
<script src="https://unpkg.com/lodash@4.16.0"></script>
```

**After**

```
<script src="https://unpkg.com/marked@0.3.6/lib/marked.js"></script>
<script src="https://unpkg.com/lodash@4.16.0/lodash.js"></script>
```

**Comment by xuanlv2** [comment]
@Xinyi2016 thank you sooo much!
It works for me now!
@icoxfog417

**Comment by serzh** [comment]
Why don't just use local copies of this js scripts and not rely on external provider?

**Comment by Yogarajece** [comment]
> app\server\templates\annotation\

I could not annotate after unloading data set, and the folder app\server\templates\annotation\ is not available in the doccano project folder..
Could you please help me on this...

Appreciate your help on this...

**Comment by Shantanu2k19** [comment]
> @xuanlv2 @huojianzhatian
> I got the same problem. Here is a quick fix by replacing
> 
> ```
> <script src="https://unpkg.com/marked@0.3.6"></script>
> <script src="https://unpkg.com/lodash@4.16.0"></script>
> ```
> 
> in the file `app\server\templates\annotation\annotation_base.html`
> 
> with the following paths:
> 
> ```
> <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.5.2/marked.js"></script>
> <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.js"></script>
> ```
> 
> After that, the annotation works well for me.
> 
> I made a pull request to fix this bug. Please let me know if you have further issues.

I am new to linux. Can you please tell where can i find this file?
it w

**Comment by Shantanu2k19** [comment]
> @xuanlv2 @huojianzhatian
> I got the same problem. Here is a quick fix by replacing
> 
> ```
> <script src="https://unpkg.com/marked@0.3.6"></script>
> <script src="https://unpkg.com/lodash@4.16.0"></script>
> ```
> 
> in the file `app\server\templates\annotation\annotation_base.html`
> 
> with the following paths:
> 
> ```
> <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.5.2/marked.js"></script>
> <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.js"></script>
> ```
> 
> After that, the annotation works well for me.
> 
> I made a pull request to fix this bug. Please let me know if you have further issues.

I'm having the same problem. I'm using linux 18.04. The demo works fine, but after logging in I cannot annotate text. The right click or selecting text doesn't  work. What should I do?

**Comment by NekroNeya** [comment]
> I'm having the same problem. I'm using linux 18.04. The demo works fine, but after logging in I cannot annotate text. The right click or selecting text doesn't work. What should I do?

https://github.com/doccano/doccano/issues/1831#issuecomment-1149392105
