### ISSUE TITLE
marked@0.3.6 error

### ISSUE THREAD

**Issue by chuckwu0** [chakki-works/doccano#49]
http://doccano.herokuapp.com/demo/text-classification/

Uncaught ReferenceError: module is not defined

![image](https://user-images.githubusercontent.com/3645632/50320968-a6a22700-0509-11e9-92e6-4172f7348159.png)

![image](https://user-images.githubusercontent.com/3645632/50320944-8d00df80-0509-11e9-931a-09f8e9d331f0.png)

**Comment by BrambleXu** [comment]
Could you provide more information about how to implement this error?
