### ISSUE TITLE
Enhancement: Let text editable for word segmentation or fix typo

### ISSUE THREAD

**Issue by loveJasmine** [chakki-works/doccano#56]

**Comment by Hironsan** [comment]
Lack of information.

**Comment by AnakTeka** [comment]
+1

I'm doing sequence to sequence labeling right now, but sometimes there are errors in grammar or some kind of typos from the data. It would be really great if we are able to fix errors directly from doccano, but instead right now I have to export data from doccano into my computer, edit, then import it back into doccano.

**Comment by loveJasmine** [comment]
yes, it is very clear and straight demands

**Comment by loveJasmine** [comment]
Is this feature on planing?

**Comment by Hironsan** [comment]
Yes. We already have an API for editing document so we can implement this feature by implementing the frontend.

But one problem is that if we edit a document with annotation in a sequence labeling project, the annotated data will become useless. An example is as follows:

```
Original Text: Plsident Obama
Annotation: {'start_offset': 9, 'end_offset': 14}

Edited Text: Plesident Obama
Annotation: {'start_offset': 9, 'end_offset': 14}  # incorrect
True annotation: {'start_offset': 10, 'end_offset': 15} 
```

One solution is that when we edit the document, we delete all their annotation. This is my thought.

**Comment by sudodoki** [comment]
well, other possible options might be:
1) only delete labels that have `start_offset` after edited character position
2) compare what are actual values for `old_doc[start_offset:end_offset] == new_doc[start_offset:end_offset]` and if they are equal, keep them (covers 1) as well as edits that are swapping chars, without adding/removing them outside of labeled items

But this might still not work for everyone

**Comment by loveJasmine** [comment]
I think it is not a big issue.
Alternative solution is, we save both original text and modified text

**Comment by icoxfog417** [comment]
Implementing data editing feature on doccano is a little overwhelming. It would be good to identify the territory of the tool.

**Comment by BwandoWando** [comment]
I support this update, I am seeing incorrectly spelled text, wrong punctuations, etc, etc. Would love to have the capability to fix typos, grammatical errors, etc, as I see them.
