### ISSUE TITLE
Feature Request: Go to specific page

### ISSUE THREAD

**Issue by axelinternet** [chakki-works/doccano#58]
# Feature request

Thanks for a great tool, feels really promising and is fast to work with. 

However for me it is really lacking a feature to go to a specific page when annotating a sequence. Say that I have 2000 sequences I want to annotate with entities, if I want to go back to sequence 1000 I have to manually go through each page. This is time consuming and somewhat error prone as one might miss to annotate some sequences.

**Comment by c-w** [comment]
I wonder if having a shortcut or button to go to the next non-labelled entry would be useful.

**Comment by axelinternet** [comment]
That would not be so useful as it wouldn't account for "correct non-labeled" entries, the entries that doesn't contain any NER tag. Some way to keep track of what has not been handled, or the ability to mark as correct without labels would be necessary.

**Comment by BrambleXu** [comment]
Usually, there are three kinds of roles in annotations process: 

A) Labeler: The labeler is responsible for marking the data.

B) Auditor: The auditor is responsible for reviewing the quality of the marked data.

C) Administrator: Manage personnel, issue tasks, and count wages.

Right now we assume `Administrator` also play the `Auditor` role. So As @c-w mentioned, it might be acceptable to add a button jump to next non-audit entry.

**Comment by olix20** [comment]
This is quite problematic for labeling/auditing large datasets. At the very least some indication in the url would be really helpful. Thanks!

**Comment by c-w** [comment]
@olix20 Note that the page information is stored in the URL so it's possible to resume long auditing sessions via bookmarking (see screenshot below):

![Screenshot showing annotation page information in URL](https://user-images.githubusercontent.com/1086421/58256113-63f4ad00-7d3c-11e9-94cc-4f30f226971e.png)

**Comment by olix20** [comment]
Thanks @c-w but that `offset=x` doesn't appear on my chrome: `http://localhost:8000/projects/6/#` 
I import data in conll format and have a few hundred prelabelled sentences (auditing).

**Comment by c-w** [comment]
@olix20 What's the version of the project you're using and/or do you see any errors in the Javascript console?

**Comment by olix20** [comment]
@c-w I don't see errors in the console. how do i check the version? I just pulled and built but still same error. thanks.

**Comment by icoxfog417** [comment]
Continue on #261
