### ISSUE TITLE
Unable to annotate any document with more than 26 labels

### ISSUE THREAD

**Issue by dveselov** [chakki-works/doccano#61]
Hi,
First of all, I must say that doccano is pretty good.
But I come with problem: doccano becomes unusable, when I need to annotate any document with more than 26 labels (example task: classification of hand-written country names: `englind -> england`, `usa -> united_states_of_america` and so on), because label can't be created without shortcut, label shortcut can't be reused and shortcuts map contains only lowercased ascii characters.

Thanks.

**Comment by dveselov** [comment]
As workaround, I've replaced `strings.ascii_lowercase` with `strings.printable` in label shortcuts choices: https://github.com/bureaucratic-labs/doccano/commit/39cc965b3618ed4fb39ab50b1fec140789e38cc2 & https://github.com/bureaucratic-labs/doccano/commit/859018bf0527dd087deec0709312e0b7755d08b4
Everything works fine for me, if this change is acceptable I can create PR (/cc @BrambleXu).

**Comment by BrambleXu** [comment]
Hi @dveselov, I am glad you work this out. 

I test your code locally. I can add labels only by clicking, but can not use the short cut keys to add `@` and `A`. Do you also only add these label by clicking? If so, this is not acceptable for a PR. If not, please make the changes in your code. 

![image](https://user-images.githubusercontent.com/10768193/50883092-56dcbe80-142a-11e9-940a-fce459814277.png)

If you add these labels only by clicking, there is no need to increase the short cut keys. You can make the short keys optional instead. 

Find `class Label` in `models.py`, modify it as below:
```
shortcut = models.CharField(max_length=10, choices=KEY_CHOICES, blank=True)
class Meta:
    unique_together = (
        ('project', 'text'),
    )
```
Then run below command in command line.
```
python manage.py makemigrations
python manage.py migrate 
```
If you have done these steps, the short keys become optional. You can add unlimited labels withoud short cut keys.

![image](https://user-images.githubusercontent.com/10768193/50884630-c81e7080-142e-11e9-9006-b1ba11b34b7c.png)

**Comment by Hironsan** [comment]
I think making short cut keys optional is a good idea. But at the same time, we should consider increasing the number of short cut keys. For example, we can increase them by combining ASCII characters and ctrl or alt keys.

**Comment by aribornstein** [comment]
I am having this issue as well having more shortcut keys would be great but I can imagine a situation i.e co-reference taggings where I have hundreds of mention tags in which case there won't be enough shortcut keys. P.S this is an amazing project :)
