### ISSUE TITLE
Different user annotate different parts of datasets in the same project?

### ISSUE THREAD

**Issue by bifeng** [chakki-works/doccano#65]
How to solve this?

**Comment by eshijia** [comment]
I also have a similar question. How to let other users work together for the data annotation within a same project?

**Comment by BrambleXu** [comment]
Right now, different users cannot work in the same project. In such a case, you can share your account with others.

**Comment by Hironsan** [comment]
doccano supports multi-user annotation. Right now, they can annotate same parts of dataset but they cannot annotate different parts of dataset.

**Comment by bifeng** [comment]
how to vote up?

**Comment by c-w** [comment]
@Hironsan Could you share any thoughts you have on design or architecture for the feature as a starting point?

**Comment by GitOffice** [comment]
> Ideally it would be nice to have N users in the system, configure it such that each sample needed atleast K judgements and then allocate it to the users on a first-come first basis till that K limit is hit.
> 
> We've had to do this in our current (much less polished) system because if users stopped tagging then pre-allocated samples would sit idle.

How do you import N users account  using doccano? Thanks in advance.

**Comment by LamDang** [comment]
@bsatts The behavior you described is probably the best, but I feel it may require a lot of changes to make real time allocation works.

How about a lesser version like this:
- documents are pre allocated and users only see theirs documents
- admin have an interface to manage and reallocate documents per user with function like transfer from one user to another, redistribute everything

What do you think?

**Comment by bsatts** [comment]
Yeah that would be pretty reasonable.

**Comment by vahidm** [comment]
Hi, Anyone busy with the implementation?

**Comment by Hironsan** [comment]
A simple solution is dynamic filtering. It is not perfect but it can filter documents by the number of annotated users. We can specify the number of annotated users by `k`. The endpoint is like <http://127.0.0.1:8000/v1/projects/1/docs?k=3>.

```python
from django_filters.rest_framework import FilterSet, NumberFilter
from django.db.models import Count
from .models import Document


class DocumentFilter(FilterSet):

    def get_k(self, queryset, name, value):
        docs = queryset.annotate(num=Count('seq_annotations__user', distinct=True))
        return docs.filter(num__lt=value)

    k = NumberFilter(method='get_k')

    class Meta:
        model = Document
```

Once we set `k` in a project, we use it when fetching documents in an annotation page.

**Comment by hankcs** [comment]
> A simple solution is dynamic filtering. It is not perfect but it can filter documents by the number of annotated users. We can specify it by `k`. The endpoint is like http://127.0.0.1:8000/v1/projects/1/docs?k=3.
> 
> ```python
> from django_filters.rest_framework import FilterSet, NumberFilter
> from django.db.models import Count
> from .models import Document
> 
> 
> class DocumentFilter(FilterSet):
> 
>     def get_k(self, queryset, name, value):
>         docs = queryset.annotate(num=Count('seq_annotations__user', distinct=True))
>         return docs.filter(num__lt=value)
> 
>     k = NumberFilter(method='get_k')
> 
>     class Meta:
>         model = Document
> ```
> 
> Once we set `k` in a project, we can use it when fetching documents in an annotation page. Annotators don't have to care about k. All things are performed in the background.
> 
> From a viewpoint of implementation, I think it does not require a lot of changes: add DocumentFilter's condition, add a column for `k` to Project model and change frontend(`search` method in annotation page).

Some documents will get annotated for more than k times, since there is no synchronization in the UI. Users click next, the data in this page remains the same as the first time this pages fetch from the server. So, the next document might be annotated by other users too.

**Comment by gabrer** [comment]
Is there any way to share the same set of labels across different projects?
This is related to the current issues because to annotated different parts of the dataset with different users  I have used a workaround, that is to create several projects with subsets of the original dataset.

**Comment by icoxfog417** [comment]
Now doccano can share the data between annotators.
