### ISSUE TITLE
Project polymorphysm base on its type

### ISSUE THREAD

**Issue by serzh** [chakki-works/doccano#66]
### Describe the problem
We have 3 project types: document classification, sequence labeling and seq2seq. All of this types are represented as a single Project class with lots of if-elses on project type. It will be more better to use inheritance and proxy model to represent these polymorphic relations. It will be easier to extend, write and reason about.

This issue was extracted from the comment in this PR #55

**Comment by BrambleXu** [comment]
Your proposal is acceptable, we will leave this issue to you. Looking forward to your PR.

**Comment by BrambleXu** [comment]
@serzh Are you still working on this? The model is changed a little and I am worried this will make trouble for your work.  And other issues might also need to change the model part too. Let me know your status.

**Comment by serzh** [comment]
@BrambleXu Sorry for the delay, have some hard days on work. I haven't started any refactoring now, I expect to start working on it within 2 weeks.

**Comment by BrambleXu** [comment]
@serzh It's totally okay. I am sorry to hear that you have bad days on work. That does sound frustrating. In the other side, it is good to hear that you haven't started the refactoring work. @Hironsan is working on this task recently and it should finish soon. After his work finished, it would be great to hear your opinion.

**Comment by serzh** [comment]
That's great! I would be happy to participate in a review.

**Comment by serzh** [comment]
Should we change `Assignee` on this task to @Hironsan ?

**Comment by Hironsan** [comment]
OK.

**Comment by Hironsan** [comment]
Done.
