### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by lhwlhw90** [chakki-works/doccano#67]
------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: centos7
- **Python version**: python 3.6
server ngnix,uwsgi

### Describe the problem
I load 600w short text （nearly 100 MB）for classification，when I request the annotate page ,the response is slow,so that return a 404。and it comsume 100% cpu. and nearly 3g memory.how could I refine its performance, is optimizing database useful?

**Comment by BrambleXu** [comment]
You can try the latest doccano because it will load data as a batch, this might alleviate this situation.

If this can not solve the problem, I recommend you split this large file into several files. 100 MB is too large.
