### ISSUE TITLE
Uploading the JSON data causes "Too many SQL variables" error.

### ISSUE THREAD

**Issue by bwkchee** [chakki-works/doccano#82]
### System information
- **Windows 10 Enterprise 1709 OS Build 16299.726**:
- **Python 3.7**: 

### Describe the problem
From a current pull from master (1/29) on Windows 10 I get the a django.db.utils.OperationError: too many SQL variables at line 132 in server/views.py in post Document.objects.bulk_create(batch, batch_size=batch_size).  

The JSON has 3 elements: { "enterprise_id":string, "encounter_id":string, "text":string} 
The json was converted from dicts in python using json.dumps. Newlines \n were replaced with |.   Each json was terminated with a \n.  It currently loads on in a linux install.  Looking at the file in notepad++ everything looks fine.  

I can't attach logs - this is running in a VM via citrix client that has copy/paste disabled.

**Comment by icoxfog417** [comment]
Thank you for reporting phenomenon.

* Could you show us some examples that you uploaded?
* How many data did you upload?
* Please check your data file encoding (UTF-8 is suitable).
* Please check you select "JSON upload" (not CSV) when you upload the data.

**Comment by bwkchee** [comment]
I was trying to upload 600 documents.  I found the problem - if I set IMPORT_BATCH_SIZE to 100 in app/app/settings.py it will work.  I think it's related to this: https://stackoverflow.com/questions/7106016/too-many-sql-variables-error-in-django-witih-sqlite3 when there are too many SQL variables in SqlLite3 see  https://www.sqlite.org/c3ref/c_limit_attached.html#sqlitelimitvariablenumber

**Comment by icoxfog417** [comment]
Thank you for detail reporting!
As you detected, this phenomenon seems to be caused by the number of parameters (that is from parameter/query x rows).

To fix this, we have to consider the tradeoff between performance and error-safe. We consider how to deal with it.

**Comment by BrambleXu** [comment]
Yes, please raise a PR, [How to Contribute to Doccano Project
](https://github.com/chakki-works/doccano/wiki/How-to-Contribute-to-Doccano-Project). 

There is acttuly a id filed for document class excpet text, metadata and project. So 200 might be a safe number. As you said, we can tolerate the performance due to the less feaquency of import data.

**Comment by zlwzlwzlw** [comment]
how can use doccano link to the Database,and import data of batches automatically

**Comment by icoxfog417** [comment]
Please let me know if this issue still occur.
