### ISSUE TITLE
Pagination (Enhancement)

### ISSUE THREAD

**Issue by bwkchee** [chakki-works/doccano#84]
For large numbers of documents some sort of pagination at the bottom of the left navigation area would be useful.  For example pagination like: < 1, 2, 3, 4, 5 > would be helpful.  It can be difficult for users to resume annotating a couple of hundred annotations in.

**Comment by BrambleXu** [comment]
This feature relates to #58.

**Comment by c-w** [comment]
In https://github.com/chakki-works/doccano/pull/79, the memoization/resume part was implemented (the implementation is pretty raw but it works). What's left to do here would be the pagination UI buttons.

**Comment by icoxfog417** [comment]
[It is considering at new UI](https://github.com/chakki-works/doccano/pull/341)
