### ISSUE TITLE
how to customise for spell check annotation?

### ISSUE THREAD

**Issue by dravishankar7** [chakki-works/doccano#85]
Feature Request: Annotation for spell check.
I need the annotated data for spell check. I have some base line system where it gives a corrected line for a given line. Now I want to compare these two lines word-by-word and annotate it like whether a word is correct or if it is incorrect, then i need to input a correct word. Is there anyway I can hack around the present code for this purpose?
Thanks in advance.

**Comment by Hironsan** [comment]
Below is an image of what you are saying. right?

![image](https://user-images.githubusercontent.com/6737785/52253622-7e9d4480-294c-11e9-98f6-9d9525081cd0.png)

**Comment by dravishankar7** [comment]
Hi Hironsan, yeah it's similar to that. That will also work. It would be really helpful. Thanks.
