### ISSUE TITLE
Create same set of labels for multiple projects

### ISSUE THREAD

**Issue by ganeshrams** [chakki-works/doccano#86]
Currently multiple users cannot share same project for annotation so I created different projects for different users. Is there anyway to create same set of labels for multiple projects.

Thanks
Ganesh

**Comment by BrambleXu** [comment]
The real thing you want to do is allowing multiple user share the same project instead of creating the same set of labels for multiple projects. This is duplicate with #65, I will close this issue. Please leave your comment in #65.
