### ISSUE TITLE
Uploading non UTF-8 csv causes UnicodeDecodeError

### ISSUE THREAD

**Issue by Hironsan** [chakki-works/doccano#88]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: any
- **Python version**: any

### Describe the problem

When we upload non UTF-8 csv, it causes UnicodeDecodeError. The problem is caused by [line74](https://github.com/chakki-works/doccano/blob/23a1aff7880e3e5c2fbd6f0930edab01782367cc/app/server/views.py#L74) in views.py. It assumes that the input file is UTF-8. Related to [this comment](https://github.com/chakki-works/doccano/issues/22#issuecomment-462646596).

### Source code / logs

```
Traceback (most recent call last):
  File "/app/server/views.py", line 121, in post
    documents = self.csv_to_documents(project, file)
  File "/app/server/views.py", line 77, in csv_to_documents
    maybe_header = next(reader)
  File "/virtualenvs/doccano-HEgudFLz/bin/../lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by icoxfog417** [comment]
Do we have to handle non UTF-8 file? If we don't support it, this issue should be closed.
