### ISSUE TITLE
Loading data from API call

### ISSUE THREAD

**Issue by alohia** [chakki-works/doccano#9]
Hi,

I want to make an api call to `POST /projects/<project_id>/docs/create` to create a document classification dataset, using Postman for example. However, I get an error saying that csrf verification failed. Can you please let me know how can I make a POST call if I need to make this call from some other program when doccano is running?

Thanks

**Comment by icoxfog417** [comment]
Now, doccano does not officialy support external API call ( #6 ). So please wait a future progress!
