### ISSUE TITLE
Project source code structure

### ISSUE THREAD

**Issue by machakux** [chakki-works/doccano#93]
Since doccano can be considered as basically a Django project, would it be useful to update directory structure to be more similar to most of typical Django projects?

The structure could be something similar to ...

```bash
doccano/   # repo/project base
    doccano/
        __init__.py
        settings.py
        urls.py
        wsgi.py

        core/  # doccano core app; Project, Documents, ...
        classifier/

    templates/ 
    static/
    tests/
    manage.py

    webpack.config.js
    package.json
    package-lock.json
    {{ webpack-app }}  # Client Side Vue/Javascript, build could be written to static/ folder

    data/
    docs/
    tools/
    requirements*
    ...
```

May be this is not a high priority issue for now but I think it could make the code structure easier to understand to more django developers and may add some convenience as project grows.

Thanks

**Comment by BrambleXu** [comment]
Thanks for the advice.
I create a new wiki and hope this meets the needs. 
[Project Source Code Structure](https://github.com/chakki-works/doccano/wiki/Project-Source-Code-Structure)
