### ISSUE TITLE
Configuration using .env

### ISSUE THREAD

**Issue by machakux** [chakki-works/doccano#94]
Currently the doccano allows overriding some of django settings using system environmet variables. That adds significant level of convenience.

Would it be better if doccano would also allow overriding system environment variables and hence django settings using `.env` file through something like https://github.com/theskumar/python-dotenv ?

The `.env` file will not be tracked by git and is already included in `.gitignore` https://github.com/chakki-works/doccano/blob/master/.gitignore#L112

**Comment by c-w** [comment]
Great idea. Opened a PR for this in https://github.com/chakki-works/doccano/pull/103.
