### ISSUE TITLE
Can doccano aspect sentiment annotation in Chinese?

### ISSUE THREAD

**Issue by GitOffice** [chakki-works/doccano#96]
I want to do aspect-based sentiment analysis and not document-based SA. In other words, if there are separated sentiments about each category  in a single sentence ,I want to annotate both.

eg. “I liked the service, but not the food”,  which be annotated as  { service:positive,food:negative}

Thanks for any response.

**Comment by BrambleXu** [comment]
You can separate the documents into sentences, and import these sentences. Then you create the labels like `service:positive`, `food:negative` and so on. Finally, you can assign labels to each sentence.

**Comment by GitOffice** [comment]
> You can separate the documents into sentences, and import these sentences. Then you create the labels like `service:positive`, `food:negative` and so on. Finally, you can assign labels to each sentence.

There is 3 aspect categories( service,food and utility) and 3 sentiments (positive ,negative and neutral) . Does it mean I will create 3*3=9  labels ,then tag  these labels for sentence if applicable?

**Comment by BrambleXu** [comment]
Yes, you are right.

**Comment by GitOffice** [comment]
> Yes, you are right.

Thanks for your time.
