### ISSUE TITLE
How to login on Heroku?

### ISSUE THREAD

**Issue by 1049451037** [chakki-works/doccano#98]
### System information
Heroku

### Describe the problem
I can do nothing but see the live demo.

**Comment by 1049451037** [comment]
Solved by following the create super user steps in README

**Comment by 1049451037** [comment]
I tried to follow the steps in README. And I created a superuser in Heroku console by running:

```
python manage.py createsuperuser
```

However, I still get ```Your username and password didn't match. Please try again.```

**Comment by 1049451037** [comment]
Besides, I tried ```./tools/create-admin.sh```. It is also not working.

**Comment by essdeee** [comment]
Following

**Comment by Hironsan** [comment]
Now we can deploy doccano by a heroku button.

**Comment by icoxfog417** [comment]
As for now, deployment to Heroku is a little difficult due to some setup process (ex: JavaScript file build process, database migration process etc).

So we prepared Heroku Button on (#101). Please try it.

**Comment by mehmetilker** [comment]
Hi @icoxfog417 
Problem here is default username password (admin/password) does not work on Heroku.
Otherwise I could install on Heroku successfully.

**Comment by mehmetilker** [comment]
@icoxfog417 ok, I got it. When we set up new heroku app, Heroku asks us to set up user name pass.
Thanks.

**Comment by moltaheb** [comment]
what if I did some modification and want to deploy it on Heroku, it's not work with me
